### ISSUE TITLE
how to use in a seperate javascript file

### ISSUE THREAD

**Issue by kaka2008** [mashpie/i18n-node#116]
i use express,in one ejs file,i import a seperate javascript file which name index.js,and how can i use i18n in index.js?

in index.js,the code is like this:
```javascript
 $this.attr("title", "cancel collect");
 $this.html("cancel collect");
```
i write below
```javascript
 $this.attr("title", "<%=__('cancel_collect')%>");
 $this.html("<%=__('cancel_collect')%>");
```
but in the page,it does look like this
```html
 <%=__('cancel_collect')%>
```

if i write the javascript code in the ejs file itself,it's right.
 so,what should i do? 
thank you!

**Comment by maamve** [comment]
This is a EJS question. Look on their site i remember seeing this there.

**Comment by mashpie** [comment]
i18n does not support client side usage out of the box (yet). Usage in templates depends heavily on template engine and middleware (express, connect, etc.).

You might get an idea from https://github.com/mashpie/i18n-node#example-usage-in-expressjs and https://github.com/mashpie/i18n-node#optionally-manual-attaching-helpers-for-different-template-engines
