### ISSUE TITLE
[req|res].setLocale() doesn't change template locale

### ISSUE THREAD

**Issue by FredKSchott** [mashpie/i18n-node#120]
`app.use(i18n.init)` sets `res.locals.locale` so that the template helpers can get the current language. However, calling `res.setLocale()` doesn't update this property, so the final page language doesn't get changed. 

```
// First Request:
app.use(i18n.init); // locale=en, res.locals.locale=en
app.use(function(req, res, next) {
  res.setLocale('ja'); // locale=ja, res.locals.locale=en
  res.render('some-template'); // template i18n helpers use locals.locale, 
                               // so page is still in english
});

// Second Request:
app.use(i18n.init); // locale = ja, res.locals.locale=ja
// ...
```

I'm not sure what the right fix is here (or even if you consider this bug), but I thought I'd open this up to start a discussion.

**Comment by mashpie** [comment]
Hi,

I'd like to catch up with that again. There have been several issue around that setLocale "thing". Would you mind helping me to define your use case in a separate test?

You might checkout

* https://github.com/mashpie/i18n-node/blob/master/test/i18n.setLocale.js
* https://github.com/mashpie/i18n-node/blob/master/test/i18n.setLocaleDefaultLanguage.js

as a starting point. I seriously want to get your example + expectation covered...

**Comment by mashpie** [comment]
related #202

**Comment by mashpie** [comment]
changed by #189

**Comment by mashpie** [comment]
watch-out for docs

**Comment by mashpie** [comment]
here they are - please also check-out updated docs https://github.com/mashpie/i18n-node#i18nsetlocale
