### ISSUE TITLE
Publish latest i18n.js to npm

### ISSUE THREAD

**Issue by abelnation** [mashpie/i18n-node#133]
Current code in git supports prefix, but the `i18n.js` in the latest npm module does not.

**Comment by Aurelsicoko** [comment]
+1

**Comment by mashpie** [comment]
god damend and blessed: 0.6.0 is public.

Thank you so much for support, patience and feedback. After more than a year there have been a couple of merges, feature additions and code changes. I have tried hard to review and test each of them. But in case I missed something or even broke any existing use case not yet covered by our tests:

Please report!

Let's start to catch up with pending request to finally reach feature freeze and start refactoring. I'd like to review all open PRs in advance though.
