### ISSUE TITLE
configure should read all *.json automagically

### ISSUE THREAD

**Issue by StefanScherer** [mashpie/i18n-node#134]
First, thanks to that great node module. It helped me adding multi language support in an HTTP server.

As we have a lot of languages, I wondered if it would help others to simplify the `configure()` function.

At the moment I have to add to the `locales` array each language.

```javascript
i18n.configure({
    locales:['en', 'de', 'fr', 'it,' 'nl', 'ro'],
    directory: __dirname + '/locales'
});
```

With every new JSON file I have to edit the code. I started to write some code with the `glob` module, but this looks very complex for such simple task. And perhaps others have the same problem.

So what about this call:

```javascript
i18n.configure({
    directory: __dirname + '/locales'
});
```

The `configure()` function just reads all *.json files automatically that exist in the `locales` folder?
So in the folder eg. a new `bg.json` is found on next start and then supports the language `bg` as well.

Is there already such a functionality or should I start a PR for this?

**Comment by dogusev** [comment]
What about this solution?
i18n.configure({
    locales: fs.readdirSync("./locale").join(',').replace(/\.json/g,'').split(',');,
    directory: __dirname + '/locale'
});

**Comment by mashpie** [comment]
thanks @dogusev - I think we could also implement similar logic when `locales` parameter is omitted.

**Comment by mashpie** [comment]
Note to myself: needs docs

**Comment by mashpie** [comment]
got that https://github.com/mashpie/i18n-node#i18nconfigure

**Comment by StefanScherer** [comment]
@mashpie Thank you! So you will release 0.7.0 soon?

**Comment by mashpie** [comment]
yep - just writing changelog

**Comment by mashpie** [comment]
done :)
