### ISSUE TITLE
setLocale must consider response.locals.locale

### ISSUE THREAD

**Issue by razorness** [mashpie/i18n-node#141]
The current i18n.setLocale() with Express 4 and Handlebars is broken. You cannot change a locale while executing a controller and get the correct locale in your template. 
Current workaround is to set response.locals.locale directly after exeuting response.setLocale().

The huge amount of stored locales and language variables in any kind of objects, looks really crazy to me. Why can't you just use a single variable in your package globally? Why it has to be bound on several positions and under serveral names like "locale" and "language"!?

**Comment by mashpie** [comment]
a global var will change with each request. This results in concurrent requests overriding each others `locale` depending theirs `language` setting in http headers.

The `locals`are _local_ values bound to a single response obj. (this originates in express' design, I think). Referring to the working express4 example (https://gist.github.com/mashpie/08e5a0ee764f7b6b1355) changing the current _local_ `locale` in a controller action should be possible by using:

```js
// request
req.setLocale('de');
// or response
res.setLocale('de');
// or response.locals (local vars in hbs template engine's internal helpers)
res.locals.setLocale('de');
```

we have to deal with (confusing...):

`language`: refers to request header
`locale`: the resulting locale setting according to this header
`locals`: just a namespace to store values isolated to this request/response

esp. handlebars is picky with `locals` - other engines' helper read their context from `res` while hbs is only reading `res.locals`. 

Actually `res.locals.setLocale('de');` results in exactly the same like setting it directly with `res.locals.locale = 'de';` using setLocale is api-safe though....

**Comment by mashpie** [comment]
also see related #202

**Comment by mashpie** [comment]
changed by #189

**Comment by Charrondev** [comment]
I'm glad this is being worked on, I was wondering for a while what was going. i18n.setLocale() and res.setLocale() don't work with Jade and express 4 either. res.locals.setLocale() does work however.

**Comment by mashpie** [comment]
now - please also check-out updated docs https://github.com/mashpie/i18n-node#i18nsetlocale
