### ISSUE TITLE
getLocale doesnt work

### ISSUE THREAD

**Issue by ericrange** [mashpie/i18n-node#143]
my website is filled with german translation but when i do ```req.getLocale()``` i get "en"
wy?

**Comment by mashpie** [comment]
no idea, without digging thru your code :)

**Comment by roboncode** [comment]
Same issued with Express 4

    exports.show = function (req, res) {
        i18n.setLocale(req, "fr");
        console.log(i18n.getLocale()) // result is "en"
    };

**Comment by ericrange** [comment]
+1

**Comment by tabone** [comment]
+1

**Comment by tabone** [comment]
+1

**Comment by mashpie** [comment]
thanks for reminder... I wanted to comment right away three weeks ago, so let me clarify now. Please do not mix global and local scopes unless intended. Setting _local_ to fr won't change any _global_ setting:

```
    exports.show = function (req, res) {
        i18n.setLocale(req, "fr");
        console.log(i18n.getLocale()) // result is "en" => from global scope
        console.log(i18n.getLocale(req)) // result is "fr" => from local scope
    };

    exports.show = function (req, res) {
        req.setLocale("fr");
        console.log(i18n.getLocale()) // result is "en" => from global scope
        console.log(req.getLocale()) // result is "fr" => from local scope
    };
```

@see https://github.com/mashpie/i18n-node/blob/master/i18n.js#L244

**Comment by mashpie** [comment]
please see 

* https://github.com/mashpie/i18n-node/blob/master/test/i18n.setLocaleDefaultLanguage.js
* https://github.com/mashpie/i18n-node/blob/master/test/i18n.setLocale.js

to clarify a bit more:

* `i18n.getLocale()`- will __always__ return the current defaultLocale
* `req.getLocale()`  - will return the current locale of `req` either set by i18n.init() or modified by `req.setLocale()` in any custom middleware
* `res.getLocale()`  - will return the current locale of `res` either set by i18n.init() or modified by `res.setLocale()` in any custom middleware

all this is _serverside_ only. Any usage in templates relies on the template engines helpers and how they apply current req|res scope. So you might need to bind your helpers in special way suitable for your template engine. Take a look at https://github.com/mashpie/i18n-node#optionally-manual-attaching-helpers-for-different-template-engines for a starting point

**Comment by mashpie** [comment]
so - please also check-out updated docs https://github.com/mashpie/i18n-node#i18nsetlocale
