### ISSUE TITLE
npm is not keep updated

### ISSUE THREAD

**Issue by martingg88** [mashpie/i18n-node#145]
the latest version in github is not keep updated with npm site. 

can anyone pls update to latest version at npm site?

**Comment by mashpie** [comment]
ok, although some features are still missing i will release what we have. 

--
mobil beantwortet

**Comment by martingg88** [comment]
thanks.

**Comment by Tontaube** [comment]
yes please :-) I'm looking forward to the accept-language improvements :-)

**Comment by mashpie** [comment]
+1

**Comment by insertc0in** [comment]
+1 ;)

**Comment by brettz9** [comment]
Could we get a npm version update please? Thanks!

**Comment by nikuph** [comment]
+1

**Comment by tjwebb** [comment]
+1

**Comment by martingg88** [comment]
+1

**Comment by jguepin** [comment]
:+1:

**Comment by vanwalj** [comment]
:+1:

**Comment by bnetter** [comment]
:+1:

**Comment by martingg88** [comment]
please make a decision faster. Thanks.

**Comment by mashpie** [comment]
God 11months... Sorry for that. I won't wait a year

**Comment by mashpie** [comment]
god damend and blessed: 0.6.0 is public.

Thank you so much for support, patience and feedback. After more than a year there have been a couple of merges, feature additions and code changes. I have tried hard to review and test each of them. But in case I missed something or even broke any existing use case not yet covered by our tests:

Please report!

Let's start to catch up with pending request to finally reach feature freeze and start refactoring. I'd like to review all open PRs in advance though.
