### ISSUE TITLE
How to get the list of locales?

### ISSUE THREAD

**Issue by zauker** [mashpie/i18n-node#147]
If in my app i want put a language switcher i need the list of availables locales.
There is a way to got it?

**Comment by einfallstoll** [comment]
You can use the new `getLocales()` API e.g. in EJS:
```
<ul>
<%- getLocales().map(function(locale) {
    return '<li>' + locale + '</li>';
}).join('') %>
</ul>
```

**Comment by zauker** [comment]
Thanks a lot @einfallstoll 
I suppose that it works correctly even with jade, tomorrow i'll try it.

**Comment by einfallstoll** [comment]
Yes, it'll work with jade as well.
