### ISSUE TITLE
Translating routes

### ISSUE THREAD

**Issue by xpepermint** [mashpie/i18n-node#150]
Please add a function which returns a list of translations for a key (as an array) so we will be able to translate express routes like the example: 

```js
var app = express();

function __l(key) {
  var translations = [];
  Object.keys(i18n.getCatalog()).forEach(function(locale) {
    translations.push( i18n.__({phrase: key, locale: locale}) );
  });
  return translations;
}

app.get( __l('/:locale/products/:id?'), function (req, res) {
  req.setLocale( req.params.locale );
  res.render('index');
  
  // this will match routes
  // /:locale/products/:id?       ... EN
  // /:locale/productos/:id?     ... ES
  // ...
});
```

**Comment by mashpie** [comment]
so you'll expect:

```js

var routes = __l('/:locale/products/:id?');

// equals - a)

routes = [
  '/:locale/products/:id?',
  '/:locale/productos/:id?'
];

// or how about - b)

routes = [
  {'en': '/:locale/products/:id?'},
  {'es': '/:locale/productos/:id?'}
];
```

**Comment by xpepermint** [comment]
Let's add the `b` as a default. If you pass `true` as a second parameter, you get the `a`. What do you think?

**Comment by xpepermint** [comment]
Even better would be the .inverse() of my proposal :). If you pass `true` for the second parameter, you get a hash (`b`) and by default an array is returned (`a`). What do you think?

**Comment by xpepermint** [comment]
@mashpie Which option do you prefer? I would appreciate if you could add this feature into next version. Thanks!

**Comment by mashpie** [comment]
hmm. liked to catchup with this in next release. Let's see if I manage that

**Comment by mashpie** [comment]
I think it's best to split:
* __l() returns a list
* __h() returns a hash
