### ISSUE TITLE
Please add aliase functions like `i18n.t`

### ISSUE THREAD

**Issue by xpepermint** [mashpie/i18n-node#154]
I think the code would look much cleaner if we could write it like `i18n.t(...)` instead of `i18n.__(...)`. It would be great if we could add short alias functions. Maybe we could set these through options.

**Comment by adambuczynski** [comment]
+1

**Comment by adambuczynski** [comment]
@mashpie just came back to see the status of this issue. Would you be interested in a PR for this feature?

My thoughts are to expose a new configuration option which can provide a string for the name of the method that gets exposed on `res`, and if provided, use that instead of `__`.

**Comment by mashpie** [comment]
go ahead - I guess a user should be able to add aliases to some or all api methods (https://github.com/mashpie/i18n-node/blob/master/i18n.js#L19).
