### ISSUE TITLE
0.5.0 Prefix not support

### ISSUE THREAD

**Issue by willin** [mashpie/i18n-node#155]
Please update the latest codes to npm

**Comment by tjwebb** [comment]
+1

**Comment by mashpie** [comment]
god damend and blessed: 0.6.0 is public.

Thank you so much for support, patience and feedback. After more than a year there have been a couple of merges, feature additions and code changes. I have tried hard to review and test each of them. But in case I missed something or even broke any existing use case not yet covered by our tests:

Please report!

Let's start to catch up with pending request to finally reach feature freeze and start refactoring. I'd like to review all open PRs in advance though.
