### ISSUE TITLE
Translation not working properly

### ISSUE THREAD

**Issue by hellowin** [mashpie/i18n-node#156]
If I typed `__('Welcome')`, it works properly. But if I typed `__('Welcome guys')` the `Welcome` phrase not translated properly. Also if I typed `__({phrase: 'Welcome guys', locale: 'en'})` it is not working properly.

I noticed it from Sails Framework as I described in [this issue](https://github.com/balderdashy/sails/issues/2902), but after I configure it manually (without Sails dependency at all, at least just like an common express app) the problem still occurs.

**Comment by mashpie** [comment]
Please check your translation files (example: https://github.com/mashpie/i18n-node/blob/master/locales/en.json): 

Does it contain your key ('Welcome guys' in your case)?
Did you setup the according translation in all of your locale files?

And in sails (https://github.com/balderdashy/sails/issues/2902):

Have you setup all desired locales?
Are you running in developent or production?

Have you setup implicit file writing:

    // whether to write new locale information to disk - defaults to true
    updateFiles: false,

**Comment by hellowin** [comment]
@mashpie thank you very much, it's not bug. It's my mistakes, that my `en.json` format is wrong synthax. Sorry to bother you. Great job guys.

**Comment by mashpie** [comment]
don't worry - glad to hear it works for you :)

**Comment by hellowin** [comment]
@mashpie I just created Dust.js helpers to be able use this i18n feature in Dust.js (for sails only for now), maybe you can check it out and give it more touch :D I need a lot of learning.
https://github.com/hellowin/sails-hook-dust-i18n sorry to bothering.
