### ISSUE TITLE
objectNotation + updateFiles = unrecognized keys error

### ISSUE THREAD

**Issue by Oneiros90** [mashpie/i18n-node#159]
Hi
This is my configuration:
`i18n.configure({
    locales:['it'],
    defaultLocale: 'it',
    objectNotation: true,
    updateFiles: true
})`;

This is my test json file:
`{
	"user": {
		"firstname": "John",
		"lastname": "Doe"
	},
}`

If i try to do this: `console.log(res.__('test'))`
I get `Cannot read property 'test' of undefined (i18n.js:503:29)`

And if i try to do this: `console.log(res.__('user.age'))`
I get `Cannot read property 'hasOwnProperty' of undefined (i18n.js:478:37)`

Is this a bug? I was expecting to have those keys added in my json file (`updateFiles` is true), is `objectNotation` breaking this feature?

**Comment by Oneiros90** [comment]
I tried it again and it works, there was a problem in my setting. Sorry

**Comment by mashpie** [comment]
glad to know it works - don't worry :)
