### ISSUE TITLE
register configuration not documented

### ISSUE THREAD

**Issue by ozum** [mashpie/i18n-node#162]
I see register configuration parameter below from #121, but couldn't find it in documents. Could you please document it.

Best Regards, 

    var anyObject = {
      __: i18n.__
    };

    i18n.configure({
      locales: ['en', 'de'],
      register: anyObject
    });

    anyObject.setLocale('en');
    anyObject.__('Hallo'); // --> Hello

**Comment by mashpie** [comment]
o k e y :)

**Comment by mashpie** [comment]
please see https://github.com/mashpie/i18n-node#some-words-on-register-option and https://github.com/mashpie/i18n-node/blob/master/test/i18n.configureRegister.js :)
