### ISSUE TITLE
Problem when mixing sprintf / mustache 

### ISSUE THREAD

**Issue by rusel1989** [mashpie/i18n-node#163]
i use object notation, but dunno if it's important, howewer i experienced some problems when mixing mustache / sprintf

If i call:
```
i18n.__.apply(null, ['errors.isLength', {path: 'something', value: 'interesting'}, 5, 90])
```
with following translation: 
```
{
  "errors": {
    "isLength": "Length of field {{path}} ({{value}})  must be in range from %s to %s characters"
  }
}
```
i got following output:
```
"Length of field  ()  must be in range from [object Object] to 5 characters"
```

**Comment by mashpie** [comment]
@oliversalzburg: ever combined those features?

**Comment by oliversalzburg** [comment]
Humm, I have not. But I somewhat doubt that it's object notation related. Let's see if I can construct a small test case.

**Comment by oliversalzburg** [comment]
@rusel1989 In your scenario, you must place the mustache parameters as the last argument to `__`, like so:

```js
var s = i18n.__.apply(null, ['errors.isLength', 5, 90, {path: 'something', value: 'interesting'}]);
```

I'm not sure if this is a documentation issue. But it doesn't seem like a bug. I wouldn't recommend mixing mustache and vsprintf though ;D

**Comment by rusel1989** [comment]
Thank you very much for reply :+1: . Maybe u could mention that the order of arguments matters here: https://github.com/mashpie/i18n-node#mustache-support .

**Comment by mashpie** [comment]
@oliversalzburg: Thank you so much - I'll take care of doks :+1:

**Comment by mashpie** [comment]
It is (it was) a documentation issue, fixed that https://github.com/mashpie/i18n-node#mustache-support and added a test https://github.com/mashpie/i18n-node/blob/master/test/i18n.api.js#L94
