### ISSUE TITLE
req.setLocale("locale") sets defaultLanguage when req.locals is not defined

### ISSUE THREAD

**Issue by PhilippBaschke** [mashpie/i18n-node#166]
I have `locales = ["de", "en"]` and no `defaultLanguage` and call `req.setLocale("de")` from my middleware function. The problem occurs when a visitor accepts another language (e.g. es). I expect the language to be set to "de" for this request and not for the whole application.

I think the following things lead to this behaviour:

`guessLanguage` calls `setLocale( req, "es" )`

`setLocale` calls `getLocale(undefined)` since none of the `ifs` evaluates to `true` which leaves the `request undefined` and therefore `request.locale` is never set
 
```javascript
  // called like req.setLocale('en')
  if (locale === undefined && typeof this.locale === 'string' && typeof locale_or_request === 'string') {
    request = this;
    target_locale = locale_or_request;
  }
```
evaluates to `false` since `req.locale = this.locale` is not set

 
```javascript
    if (request === undefined) {
      defaultLocale = target_locale;
    }
``` 
evaluates to `true` since the `request` is still `undefined` which leads to a redefinition of the default Locale (unwanted behavior)

**Comment by mashpie** [comment]
this is definitely also related to #189 - the defaultLocale won't get modified any more. No matter where setLocale tries to set an unsupported locale: getLocale always returns defaultLocale.

I hope to have understood your use case which I tried to cover in the regression test `i18n.setLocaleDefaultLanguage.js`

**Comment by PhilippBaschke** [comment]
Thank you! As far as I can remember (and understand the regression test) the regression test covers my use case perfectly. Thank you again! :+1:
