### ISSUE TITLE
Allow addition and removal of locales on-the-fly

### ISSUE THREAD

**Issue by acontreras89** [mashpie/i18n-node#168]
It would be nice to have the ability to add/remove locales on-the-fly (i.e., after `i18n` has been configured with a set of locales).
I believe this can be achieved by invoking the `configure` method subsequent times, passing the updated array of locales. However, this strategy requires that all other configuration options are passed in each call as well, or they get overridden with default values.

Could we add `addLocale` and `removeLocale` methods to allow this? I'd gladly prepare a PR with the changes.

**Comment by acontreras89** [comment]
Subsequent calls to the `configure` method will allow new locales to be added, but will not delete those that were already set even if they are no longer included in the options.

**Comment by acontreras89** [comment]
Another option would be to add a single method, `setLocales` (since there's already a `getLocales` method), to override current locales.

**Comment by acontreras89** [comment]
Feature added in 45116ab.

**Comment by tomasdev** [comment]
This isn't documented in the README and it's a GREAT feature man!
