### ISSUE TITLE
Support for existing po files

### ISSUE THREAD

**Issue by perrin4869** [mashpie/i18n-node#173]
Hi, I've been wondering if there's any way to convert po files to json to be used with i18n-node. Thanks!

**Comment by mashpie** [comment]
Hey, I guess https://github.com/mikeedwards/po2json should do the job although I don't know if you need to setup a special format for i18n. Tell your thoughts if it helpped.

**Comment by perrin4869** [comment]
I see! Just tried it, and in my (extremely simple case, no pluralization etc), `po2json locale/en/LC_MESSAGES/messages.po en.json -p --format mf` did the trick... although I'm not sure if it'll work in the general case. The other 2 formats (`raw` and `jed`) output json that cannot be out out of the box
