### ISSUE TITLE
develop mode support?

### ISSUE THREAD

**Issue by ruandao** [mashpie/i18n-node#174]
My server use a lot of middleware, and the server start slowly

When edit language file to add new sentence, I have to restart server each time to make it display correct

Can i set some variable to make cache disable?

Thank you!

**Comment by mashpie** [comment]
I guess, you'd like to get a `reloadLocales()` api, right?

**Comment by ruandao** [comment]
thank you!

**Comment by mashpie** [comment]
https://github.com/mashpie/i18n-node/commit/e16e51a1a048ae88ef03ccdd184b951b7ebcadad works for you? (still needs docs & tests)
