### ISSUE TITLE
Simpler dot notation for plurals

### ISSUE THREAD

**Issue by waynebloss** [mashpie/i18n-node#177]
When using dot notation with plurals, I have to pass the key to the pluralized term twice, like `__n('cats.n', 'cats.n', 1)`, which is fine when I'm also setting the default phrases, like `__n('cats.n:%s cat', 'cats.n:%s cats', 1)`.

However, when not setting the default phrases, it would be nice to only have to pass it once .e.g., `__n('cats.n', 1)`.

```json
"cats": {
    "n": {
      "one": "%s cat",
      "other": "%s cats"
    }
  }
```

**Comment by waynebloss** [comment]
It looks like when I call `__n('dogs.n:%s dog', '%s dogs', 2)` the key is taken from the singular, so that's reasonable if I'm going to set the default phrase everywhere.

Also, this works! `__n('cats.n', '', 99)` so that is an acceptable workaround for me at this time, it's better than passing the key twice.

**Comment by mashpie** [comment]
__n() will support a short signature with 2 parameters soon... better plurals are on their way

**Comment by mashpie** [comment]
actually this is already supported, docs need refurbish but see https://github.com/mashpie/i18n-node#basic-plural-support and https://github.com/mashpie/i18n-node#ranged-interval-support

and hope it keeps rainin' cats 'n dogs so I am able to spend more time on i18n ;)
