### ISSUE TITLE
'accept-language' has not been fully taken advantage of.

### ISSUE THREAD

**Issue by Corey600** [mashpie/i18n-node#186]
When I read the function named 'guessLanguage', I found that, if 'accept-language' has two or more languages and regions, only the first is effective. If the first is not in the 'locales' list of i18n.configure, 'defaultLocale' is effective.That is not reasonable. Maybe, the second one in accept-language is more better when it is in the 'locales' list of i18n.configure.

**Comment by mashpie** [comment]
pr welcome :) - of you'd like to improve

**Comment by Corey600** [comment]
All right, this problem has been improved by mattwiller at 6e69292 committed on 10 Jul 2014.
' https://github.com/mashpie/i18n-node/commit/6e692927508958668aea68154a7a92b634082ae6 '
But it is in 0.6.0. What I ma using is 0.5.0.
Please update 0.6.0 to npm, thx.
