### ISSUE TITLE
applyAPItoObject always assigns to request, never to response

### ISSUE THREAD

**Issue by vseryakov** [mashpie/i18n-node#189]
Hi,

There is a bug in the i18n.applyAPItoObject method, it uses 'request' all the time but should use 'object' variable.

line 313 should be:
return i18n[method].apply(object, arguments);

or better make it to assign to a single object, 2 arguments seems not needed in this case

Thanks

**Comment by mashpie** [comment]
you are absolutely right. Thanks for spotting. I think people using any kind of `res.setLocale()` suffered from this. I changed that and added a regression test.

**Comment by mashpie** [comment]
...nasty setLocale - been implemented too fast and too lazily tested
