### ISSUE TITLE
Enhanced pluralize

### ISSUE THREAD

**Issue by Alexeyco** [mashpie/i18n-node#19]
Ok,

```js
// 1 apple
__n('%s apple', '%s apples', 1);

// 3 apples
__n('%s apple', '%s apples', 3);
```

For english languge it's awesome, but for (as example) russian it's wrong. I mean:

```
{
    // Singular (or 21... 31... 121... 131...)
    "1 apple": "1 яблоко",

    // Plural (2-4, 22-24, 32-34... 122-124...)
    "2 apples": "2 яблока", 

    // Plural (5-20, 25-30, 35-40... 105-120...)
    "5 apples": "5 яблок" 
}
```

Are there any plans like that?

**Comment by jesucarr** [comment]
What about implementing MessageFormat? it was built by ICU to solve this problems. Have a look at this library: https://github.com/SlexAxton/messageformat.js

**Comment by mashpie** [comment]
messageformat is really nice. I am actually thinking of an i18n.__mf() api that delegates directly to mf. Personally I don't like that ICU Format, but people will probably make use of it and should get that choice. 

I close this issue now in favor of #42 as I collected some other proposals there too and... of course of... hay it's "42"!
