### ISSUE TITLE
i18n version 0.6.0

### ISSUE THREAD

**Issue by creativityjuice** [mashpie/i18n-node#198]
Hey,

I noticed that the version on GitHub is 0.6.0 and include the new fallbacks feature, but on npm the newest version is 0.5.0 without fallback.
Would it be possible to commit the 0.6.0 on npm ?

Thanks for your work on that package !

**Comment by mashpie** [comment]
my personal schedule for this release ist Sunday :)

**Comment by creativityjuice** [comment]
Great, thanks :+1:

**Comment by mashpie** [comment]
god damend and blessed: 0.6.0 is public.

Thank you so much for support, patience and feedback. After more than a year there have been a couple of merges, feature additions and code changes. I have tried hard to review and test each of them. But in case I missed something or even broke any existing use case not yet covered by our tests:

Please report!

Let's start to catch up with pending request to finally reach feature freeze and start refactoring. I'd like to review all open PRs in advance though.
