### ISSUE TITLE
Translation with special characters

### ISSUE THREAD

**Issue by Paxa** [mashpie/i18n-node#200]
I try to write some non-latin characters and it says `unable to parse locales from file ... is empty or invalid json?`

Will it be possible to read locales file as JS files instead of JSON? e.g.

```js
locales[locale] = eval('var a = ' + localeFile + '; a');
```

Or may be let people to override `read` function? So people may use yaml or database or anything

**Comment by mashpie** [comment]
I bet, your json is broken. As you might see in https://github.com/mashpie/i18n-node/blob/master/examples/express-cookies/locales/ar.json i18n is not limited to latin at all.

**Comment by Paxa** [comment]
Right, my json was not correct. Sorry

**Comment by mashpie** [comment]
ok, glad to know any way :)
