### ISSUE TITLE
Not working using nunjucks after update  to 0.6

### ISSUE THREAD

**Issue by Paxa** [mashpie/i18n-node#202]
Set it as:

```js
res.setLocale('nl');
res.render('payment_page', {...});
```

found solution:

```js
res.setLocale('nl');
res.locals.locale = request.getLocale(); // this solves problem
res.render('payment_page', {...});
```

**Comment by mashpie** [comment]
assuming you have defined `request` elsewhere, this

```js
res.locals.locale = request.getLocale(); 
```

will copy the current locale from `request.locale` to `res.locals.locale`. Ok. you have set locale of res by yourself which will just change `res.locale`. So let's sum up what's happening to your lifecycle:

somewhere i18n get's configured and probably inited. Later you set some locales by yourself and gain more control (more control leads to more responsibilities :) ), Ok watchout what'll happen if a client with language headers of 'en' will request your setup:

```js
i18n.init(req, res);

/* 
    now we have:

    req.locale === 'en'
    req.locals.locale === 'en'
    res.locale === 'en'
    res.locals.locale === 'en'
*/

res.setLocale('nl');

/* 
    now we have:

    req.locale === 'en'
    req.locals.locale === 'en'
    res.locale === 'nl' <--- the only change
    res.locals.locale === 'en'
*/

res.locals.locale = req.getLocale();

/* 
    now we have:

    req.locale === 'en'
    req.locals.locale === 'en'
    res.locale === 'nl'
    res.locals.locale === 'en' <--- is set to the value of req.locale 
*/
```
problem is that i18n.init on the one hand sets locale properly to all 4 objects (request & response in backend & frontend) while on the other hand i18n.setLocale() only updats _one_ object and you decide which that should be (also see https://github.com/mashpie/i18n-node/blob/master/test/i18n.setLocale.js).

So for now I'd propose to implement your use case in your individual way, like so:

```js

var setAppLocales = function(req, res, locale){
    // request backend
    req.setLocale(locale);

    // request template
    req.locals.setLocale(locale);

    // response backend
    res.setLocale(locale);

    // response template
    res.locals.setLocale(locale);
}

app.get('/some', function(req, res){
    setAppLocales(req, res, 'nl');
    res.render('payment_page', {...});
});
```

it's planed to add some more convenience in here like configuring those bindings setLocale will update via the `register` option.

**Comment by mashpie** [comment]
the api could have behaved differently before 0.6.0. Using setLocale was mixing req, res and defaultLanguage in unpredictable ways (#189) depending on use case, which was a bug on older versions.

**Comment by mashpie** [comment]
please check with last commit. 

```js
res.setLocale('nl');
```
should now work out as expected.

please check out https://github.com/mashpie/i18n-node/blob/master/examples/express4-setLocale/index.js#L28 as docs & tests are not ready yet

**Comment by mashpie** [comment]
...and  - please also check-out updated docs https://github.com/mashpie/i18n-node#i18nsetlocale
