### ISSUE TITLE
Not working after update to 0.6

### ISSUE THREAD

**Issue by and07** [mashpie/i18n-node#203]
```
...

app.use(i18n.init);

app.use(express.static(settings.static_dir));

app.use(function (req, res, next) {
  if (req.session.locale) {
    i18n.setLocale(req, req.session.locale);  //problem
  }
  next();
});

...

    app.get('/:locale', function(req, res, next){
      var locale = req.params.locale;
      if(locale =='de' || locale =='en'){
        req.session.locale = req.params.locale;
        res.redirect('back');
        return;
      }
      next();
    });

...

template

{{__('hello')}}

```

**Comment by mashpie** [comment]
could you please outline a bit more precisly what to expect from your implementation. Esp. how is req.session handled. How is i18n bound to your (which?) template engine. How does this template engine handle helpers and local data?

Maybe related to #202  and #189

**Comment by and07** [comment]
0.5 everything works/ 0.6 doesnt work

1. express 4
2. template engine nunjucks

code config

var express = require('express');
var session = require('express-session');
var i18n = require('i18n');

i18n.configure({
// setup some locales - other locales default to en silently
locales: settings.locales,
defaultLocale: settings.defaultLocale,
// where to store json files - defaults to './locales'
directory: __dirname + settings.locales_dir,
objectNotation: true
});


links /de/ or /en/ 
adds to session -   locales de or en
than we take it from session and setting locales

i18n.setLocale(req, req.session.locale);

**Comment by mashpie** [comment]
please read #202 and consider:

```js
var setAppLocales = function(req, res, locale){
    // request backend
    req.setLocale(locale);

    // request template
    req.locals.setLocale(locale);

    // response backend
    res.setLocale(locale);

    // response template
    res.locals.setLocale(locale);
}

app.get('/some', function(req, res){
    setAppLocales(req, res, 'nl');
    [...]
});
```

the implementation of setLocale was wring in 0.5.0 as it changed defaultLanguage resulting in faulty fallbacks and unpredictable results. Now setLocale works as intended: Only change locale in **one** given object. 

The old 'bug' probably lead to a working implementation in your case. In 0.7.0 we will publish a configuration option for better controll how and to which scopes setLocale should apply. Until than, please consider implementing another more explicit setting of locales (ex. above) or stick to 0.5.0 until release of 0.7.0. 

I am sorry for confusion... setLocale has been around with this bug for a while and I hope not too many implementations relied on that bug. If it worked in 0.5 with:

```js
i18n.setLocale(req, req.session.locale);
```

it should work in 0.6 with:

```js
i18n.setLocale(req, req.session.locale);
i18n.setLocale(res, req.session.locale); // <--- set same locale to res also
```

prior to 0.6. setLocale was modifying defaultLanguage also. With that modified setting any `res.locale` read that default as fallback and so "seamed" to work correctly. 

But changing the global 'static' defaultLanguage will obviously lead to concurrency issues under load.

**Comment by and07** [comment]
doesnt work

```
app.use(function (req, res, next) {
  if (req.session.locale) {
    
    i18n.setLocale(req, req.session.locale);
    i18n.setLocale(res, req.session.locale);
    console.log('---'+i18n.getLocale()+'---');
  }
  next();
});

```


this

```
    app.get('/:locale', function(req, res, next){
      var locale = req.params.locale;
      if(locale =='ru' || locale =='en'){
        setAppLocales(req, res,locale); // set locales
        req.session.locale = req.params.locale;
        res.redirect('back');
        return;
      }
      next();
    });   
```
return this **Cannot read property 'setLocale' of undefined**

**Comment by and07** [comment]
this works

```javascript
var setAppLocales = function(req, res, locale){
    // request backend
    req.setLocale(locale);

    // request template
    //req.locals.setLocale(locale);

    // response backend
    res.setLocale(locale);

    // response template
    res.locals.setLocale(locale);
}
app.use(function (req, res, next) {
  if (req.session.locale) {
        setAppLocales(req, res, req.session.locale);
        //i18n.setLocale(req, req.session.locale);
        //i18n.setLocale(res, req.session.locale);
        console.log('---'+i18n.getLocale()+'---');
  }
  next();
});
```

whay?

**Comment by mashpie** [comment]
First you are mixing scopes. I18n.getLocale() is global while req.setLocale() is bound to req **only**

Second, req.locals might mit exist in your req object as all those objects depend in your own implementation. That said: there is now copy&paste solution.

And without debugging your complete setup and code I realy can't help a lot besides pointing to some ideas.

**Comment by mashpie** [comment]
You need to know how your app handels req and res objects in a request/response lifecycle. And you need to Know how to pass backend parameters to your template helpers.

I18n.init() tries to bind its helpers and params to req, req.locals, res and res.locals if defined as these were common to many frameworks and template engines. Again you might need to do those bindings in another special way depending on your modules.

**Comment by mashpie** [comment]
this

```js
var setAppLocales = function(req, res, locale) {
  // request backend
  req.setLocale(locale);

  // response backend
  res.setLocale(locale);

  // response template
  res.locals.setLocale(locale);
}

app.use(function(req, res, next) {
  if (req.session.locale) {
    setAppLocales(req, res, req.session.locale);
  }
  next();
});
```

is effectivly same implementation like 

```js
app.use(function(req, res, next) {
  if (req.session.locale) {

    // request backend
    i18n.setLocale(req, req.session.locale);

    // response backend
    i18n.setLocale(res, req.session.locale);

    // response template
    i18n.setLocale(res.locals, req.session.locale);
  }
  next();
});
```

resulting in i18n binding to three objects (`req`, `res` and `res.locals`). You still need to figure out, which one is needed by your template engine - I bet it's `res.locals`. And if so you might focus your code on implementing just this:

```js
app.use(function(req, res, next) {
  if (req.session.locale) {
    // bind to response template only
    i18n.setLocale(res.locals, req.session.locale);
  }
  next();
});
```

**Comment by and07** [comment]
Thank you so much

**Comment by mashpie** [comment]
please also check-out updated docs https://github.com/mashpie/i18n-node#i18nsetlocale
