### ISSUE TITLE
Concurrency issues with 0.7

### ISSUE THREAD

**Issue by gzurbach** [mashpie/i18n-node#209]
I'm observing a strange behavior with concurrent requests. I have read all the issues on that matter and I think I'm using the library (0.7) properly (i.e. not using global `i18n.setLocale()`).

**app.js**
```javascript
var app = express();

// Add helpers to handlebars
app.use(function(req, res, next) {
  handlebars.registerHelper('i18n', function() {
    return i18n.__.apply(req, arguments);
  });
  next();
});

// Configure i18n
i18n.configure({
  objectNotation: true,
  locales: ['en', 'fr'],
  defaultLocale: 'en',
  directory: path.join(__dirname, '/locales/server')
});

app.use(i18n.init);
```

**routes/foo.js**
```javascript
var sendEmail = function(req, res, next) {
  var locale = req.user.preferredLocale; // can be 'fr' or 'en'
  req.setLocale(locale);
  handlebars.render('email.hbs', { firstName: 'John' });
}
```

**views/email.hbs**
```javascript
{{i18n 'common.hello' firstName}}
```

When I render one email at a time, either in english or french, it works fine. But if I send 2+ emails in a `for` loop I'm starting to get emails in random languages. It seems that each time I run the loop I get different languages.

To your knowledge, is the configuration above correct? I read the code of `setLocale` and I don't see where the locale could leak from a `req` to another. But how can you explain that the issue only occurs when sending multiple requests in a short amount of time?

**Comment by mashpie** [comment]
I will try to reproduce that in a Test. Hbs has always been tricky to handle. My first guess would be to change the sequence to 

1. configure
2. init
3. use (with hbs binding)

To wire i18n up

**Comment by gzurbach** [comment]
Sorry for the noise I just figured out what the issue was. Long story short, the app was sharing a single instance of Handlebars.

The solution consists in using the `data.root.locale` from the last argument of the helper.
```javascript
app.use(function(req, res, next) {
  hbsInstance.registerHelper('i18n', function() {
    var args = Array.prototype.slice.call(arguments);
    var options = args.pop();
    return i18n.__.apply(options.data.root, args);
  });
  next();
});
```
I had tried this solution a while ago but because emails are rendered outside of a `req/res` context the `locale` was not present in `data.root`. I had to pass it manually. That was one of the most painful debugging I had to do in a while :)

Thanks for your help!

**Comment by mashpie** [comment]
Is your for loop handling req correctly? How did you implement that?

**Comment by gzurbach** [comment]
The code base is pretty big it'd be hard to share something meaningful. 

I have a `mailerService` that contains a bunch of methods to send emails. That service is used by express routes, but can run independently of any express context. The issue was that the service would share a unique instance of handlebars across the app. 

Therefore I had two options: one was two make sure each request would get and pass its own instance of handlebars to the service, the other was to pass the current locale to my handlebar template (i.e. as rendering context) so the helper knows what locale to use.

The `for` loop is located in a client which calls the REST API sending the emails. The issue did not come from there that I am sure.

**Comment by mashpie** [comment]
ah ok `options.data.root` vs `req` :) 

You're not alone, people tend to believe in magik and skip binding to "their" appropriate objects time over time. I started a gitbook for examples and walkthroughs to get that explained in depth.

**Comment by adyz** [comment]
What handlebars npm module did you used here? 
With the `hbs` module shipped  with the express-generator I still have issues with the concurrent requests.

**Comment by mashpie** [comment]
this is a (stripped down) working setup, recently launched to production:

```js
'use strict';

var express = require('express');
var app = express();
var http = require('http').Server(app);
var exphbs = require('express-handlebars');
var i18n = require('i18n');
var path = require('path');

var config = {
  baseurl: '/',
  bind: '127.0.0.1',
  port: '6000'
};

i18n.configure({
  locales: ['de', 'en'],
  defaultLocale: 'de',
  directory: path.join(__dirname, '..', 'locales')
});

app.engine('hbs', exphbs({
  defaultLayout: 'default',
  extname: 'hbs'
}));

app.set('view engine', 'hbs');
app.use(i18n.init);

http.listen(config.port, config.bind, function() {
  console.log('open http://' + config.bind +
      ':' + config.port + config.baseurl);
});
```

as you can see, there is no manual binding of i18n helpers needed. But you need to keep an eye on your templates, like in that partial:

```hbs
{{#error.message}}
    <div class="alert alert-danger" role="alert">
        {{@root.__ this}}
    </div>
{{/error.message}}
```

...helpers get attached to root-context (@root.__) only but keep locales of current request ciycle.

I'll publish some demo-projects soon... and move examples stay tuned.

**Comment by gzurbach** [comment]
I use `espress-handlebars` as well. Here is the relevant code in my app:

`app.js`
```
expressHandlebars = require('express-handlebars');

var hbs = expressHandlebars.create({
  extname: '.hbs'
});

hbs.handlebars.registerHelper('i18n', function() {
  var args = Array.prototype.slice.call(arguments);
  var options = args.pop();
  return i18n.__.apply(options.data.root, args);
});
```

Then when I send an email, I have to pass the desired `locale` as a "context":
```
sendEmail({
  from: 'foo@bar.com',
  to: 'bar@foo.com',
  subject
}, {
  message: message,
  locale
});
```

This is the only way for `options.data.root` to contain the right locale. Let me know if you need further details.
