### ISSUE TITLE
 i18n can't handle single accept-language.

### ISSUE THREAD

**Issue by mushroomsir** [mashpie/i18n-node#213]
It's invalid if accept-language is zh-CN,en,* . Can you fix it ?

https://github.com/mashpie/i18n-node/blob/master/i18n.js#L717

**Comment by mashpie** [comment]
please outline, what you expect - refer too https://github.com/mashpie/i18n-node/blob/master/test/i18n.api.local.js#L47 ff

**Comment by mushroomsir** [comment]
thank you for your help, it's resolved.
