### ISSUE TITLE
Get access for defaultLocale value

### ISSUE THREAD

**Issue by DJviolin** [mashpie/i18n-node#225]
Is there a way to get acess for the `defaultLocale` value from `i18n.configure()`?

I'm adding the active language's name to my `html` div in app.js with:

```
var langClass = function(req, res, next) {
  //var defaultLang = 'en';
  var defaultLang = req.defaultLocale();
  var activeLang = req.params.lang || defaultLang;
  res.locals.langClass = activeLang + '-' + activeLang.toUpperCase();
  next();
};
```

Which is rendered in the template like:

```
<!doctype html>
<html class="no-js lang-en-EN" lang="en-EN">
```

Is there a way to achieve this? I searched in the documentation but I didn't found it.

**Comment by mashpie** [comment]
`defaultLocale ` is static. You set it you get it form within you code. What you actually need is `i18n.getLocale(req)` to get the current locale handled by that current request.

**Comment by DJviolin** [comment]
Thank You! That's much simple!
