### ISSUE TITLE
Posting a Log Message when Translation is missing for Locale 

### ISSUE THREAD

**Issue by DServy** [mashpie/i18n-node#230]
I have a usage case for need to fire a custom log message if a translation is missing for a given Locale. E.g., if I have a phrase "Register Your awesome User" that never got translated in the de file, I want to fire an info log that informs us that "Register Your Awesome User" does not have a german (de) translation.

Is there a current way of getting a log like this fired? If not, do you guys feel like it would be useful to enable that type of functionality? # #

**Comment by mashpie** [comment]
that case should end up in https://github.com/mashpie/i18n-node/blob/master/i18n.js#L844 - yes that waring message states a bit missleading... could be refactored sooner

**Comment by mashpie** [comment]
improved by config option for callback function:

```
js
    // used to alter the behaviour of missing keys
    missingKeyFn: function (locale, value) {
        return value;
    },
```
