### ISSUE TITLE
We should make i18n-node much stricter.

### ISSUE THREAD

**Issue by dangreen** [mashpie/i18n-node#234]
1) We can set custom objectNotation character, `.` by default. For example we can set `:` character, but this character [sets default values](https://github.com/TrigenSoftware/i18n-node#defaults).
2) With objectNotation we still can use `__("Simple sentence with dot.")` (https://github.com/mashpie/i18n-node/pull/210,  https://github.com/mashpie/i18n-node/pull/235), but  `__("Simple sentence with dot. Try it") + ":"` parsed as path. 
3) With objectNotation `__("Error: user not found.")` parsed as "Error" key with  default value " user not found."
etc...

We have two ways: 
1) Forbid using of whitespace with objectNotation. If string contains whitespace - skip handling it as path.
2) Leave all as is, but add `mixedMode` option to enable all from first point.

We should talk about it and decide which way we should choose. And i can help with implementation.

**Comment by oliversalzburg** [comment]
I don't understand why you would even use object notation if those were your use cases. Your string literals are supposed to be abstract descriptions which serve as lookups into a tree. If you're just using plain strings, don't use object notation.

**Comment by dangreen** [comment]
@oliversalzburg I talk about mixed using of objectNotation and plain strings.

**Comment by dangreen** [comment]
@oliversalzburg current code presupposes using plain strings with objectNotation, but not fully.

**Comment by mashpie** [comment]
first off: we all should be on vacation today :)

there are some more options to handle a mixed setup:

1. adding explicit api methods for strict handling of objects and strings `__o()`  `__$()`
2. adding optional paramters to all methods like `{asString: true}` to enforce a certain processing
3. most consistant to my use cases would be the option to mask a delimiter __('`just my 2 cent\. take or leave?`') as we all are used to mask those or similar 
4. checkout flat (https://www.npmjs.com/package/flat) to might help
5. encapsulate strings when using objectNotation `__('"Error: user not found."')` or `__('{{{Error: user not found.}}}')` and let mustache prepare the rest... etc. etc.

in the end `i18n` right now can handle either objects or strings consistently. Any kind of mix should be handled with caution - we're devs, we know that difference

**Comment by mashpie** [comment]
ah, yes and finally: 

6. process keys as string when "ending with dot" OR "containing dot followed by whitespace" => `/\.$/ || /\.\s+/`

**Comment by oliversalzburg** [comment]
Then I don't understand why this ticket calls for making i18n *more* strict. It is very strict in that it supports either format. Mixing formats would mean making it *less* strict.

**Comment by dangreen** [comment]
@oliversalzburg 
> current code presupposes using plain strings with objectNotation, but not fully.
https://github.com/mashpie/i18n-node/blob/master/i18n.js#L925 `0 < indexOfDot && indexOfDot < singular.length` (actually `0 < indexOfDot && indexOfDot < singular.length - 1`) check if dot is first or last character then it not a path. e.g. "Test sentence.", but "Error: Test sentence." doesn't work.

@mashpie first 5 variants works only if we know in advance the type of key (string or path). 

About last variant, i think in result it should be something like this:
```js
...
var delimiter = new RegExp("\\s\\" + objectNotation + "|\\" + objectNotation + "\\s");
...
// https://github.com/mashpie/i18n-node/blob/master/i18n.js#L858
if (objectNotation) {
      var indexOfColon = singular.search(/:\S/);
...
// https://github.com/mashpie/i18n-node/blob/master/i18n.js#L925
// https://github.com/mashpie/i18n-node/blob/master/i18n.js#L991
if (objectNotation && !delimiter.test(singular) && (0 < indexOfDot && indexOfDot < singular.length - 1)) {
...
```

**Comment by oliversalzburg** [comment]
Interesting, but it was not my intention to allow for mixed content when I originally wrote that code.

It was just an optimization so that the simple `else` branch is used when you access an element at the root of the translation tree.

**Comment by dangreen** [comment]
I offer to add new option to turn on mixed keys.

**Comment by mashpie** [comment]
> @mashpie first 5 variants works only if we know in advance the type of key (string or path).

sure, and I guess a developer should know what's his intention when mixing `__('Database Error: user not found.')` with `__('Validation.Error.Required: %s is mandatory')`

intended json:

```json
    {
        "Validation": {
            "Error": {
                "Required": " %s is mandatory"
            }
        },
        "Database Error: user not found.": "Database Error: user not found."
    }
```

objectNotation === false:

```json
    {
        "Validation.Error.Required: %s is mandatory" : "Validation.Error.Required: %s is mandatory",
        "Database Error: user not found.": "Database Error: user not found."
    }
```

objectNotation === true:

```json
    {
        "Validation": {
            "Error": {
                "Required": " %s is mandatory"
            }
        },
        "Database Error": "user not found."
    }
```

I don't see any chance to teach i18n guessing all intended use cases with a hint.

**Comment by mashpie** [comment]
It might help to try multiple possible keys for finding. Example

`__('Database Error: user not found.')`

should 1st try to find the whole string `Database Error: user not found.` as key and stop or if none found also try `Database Error` as key.

```json
    {
        "Validation.Error.Required": " %s is mandatory",
        "Database Error: user not found.": "Database Error: user not found."
    }
```

with json objects flattened internaly i18n would than also try a search for `Validation.Error.Required: %s is mandatory` and fail but next find `Validation.Error.Required`

This has to be tested carefully against all known use cases, though. And I still need a reasonable default for writing with `updateFiles: true`...
