### ISSUE TITLE
How to change locale through the language picker

### ISSUE THREAD

**Issue by iaptsiauri** [mashpie/i18n-node#237]
This is my configuration but locale doesn't change, if I change defalutLocale in initial configuration webpage is translated. But if I pick different language from the dropdown nothing changes

```
i18n.configure({
  locales: ['eng', 'rus'],
  defaultLocale: 'rus',
  directory: __dirname + '/static/locales',
  cookiename: 'locale'
});

app.use(function (req, res, next) {
    res.locals.__ = res.__ = function() {
        return i18n.__.apply(req, arguments);
    };
    next();
});

app.get('/:locale', function (req, res) {
    res.cookie('locale', req.params.locale);
    i18n.setLocale(i18n, req.params.locale);
    res.redirect(req.headers.referer);
});
```

**Comment by mashpie** [comment]
3 things to consider:

1. does your cookie get set correctly, like you try with `res.cookie('locale', req.params.locale);`
2. I am missing any `app.use(cookieParser());` `app.use(i18n.init)` (https://github.com/mashpie/i18n-node/blob/master/examples/express4-cookie/index.js#L13) in your listing which are needed to parse cookies from request and initialize i18n with their value.
3. your `i18n.setLocale(i18n, req.params.locale);` is useless and wrong. Setting the cookie and redirecting should do job. And if you need to use setLocale you should pass the correct object (https://github.com/mashpie/i18n-node#i18nsetlocale) like so `i18n.setLocale(req, req.params.locale);` But this, again only affects the current request until redirecttion.

And another note :) your binding of helpers is done by i18n.init(), too. So you won't need to that by yourself. So all in all it should read like so:

```js
i18n.configure({
  locales: ['eng', 'rus'],
  defaultLocale: 'rus',
  directory: __dirname + '/static/locales',
  cookiename: 'locale'
});

// beware of the order
app.use(cookieParser());
app.use(i18n.init);

app.get('/:locale', function (req, res) {
  res.cookie('locale', req.params.locale);
  res.redirect(req.headers.referer);
});
```

**Comment by iaptsiauri** [comment]
I made changes according to your suggestions but I am still missing something.

```
var cookieParser = require('cookie-parser');
var i18n = require('i18n');

i18n.configure({
  locales: ['eng', 'rus'],
  defaultLocale: 'rus',
  directory: __dirname + '/lib/locales',
  cookiename: 'locale'
});

app.use(cookieParser());
app.use(i18n.init);

app.get('/:locale', (req, res) => {
  res.cookie('locale', req.params.locale);
  console.log(req.cookies.locale);
  res.redirect(req.headers.referer);
});
```

**Comment by mashpie** [comment]
haha I didn't spot that either... cookie vs. cookiename - the later is more explicit => thinking of an alias....

**Comment by iaptsiauri** [comment]
I will post in this question cause it is related anyways. I have handlebar helper which does the concatenation, and according to docs `i18n.__` should use the locale which is set, but concatenated string is always in defalutLocale 
```
hbs.registerHelper('concat', function(first, second) {
  return new hbs.SafeString(
    i18n.__([first,second].join('.'))
  );
});
```

**Comment by mashpie** [comment]
hbs helpers are always tricky to implement as they maintain their own scope[s] in nested levels. I recently  setup some helpers by use of `this.__()` in helper methods. Beware that this will only work on @root level  in hbs:

setup express app

```js
// app.js

var exphbs = require('express-handlebars');
var helper = require('./helper');

/**
 * setup templating / rendering
 */
app.engine('hbs', exphbs({
  defaultLayout: 'default',
  extname: 'hbs',
  helpers: helpers(app)
}));
```

and a helper module combining all of my helpers:

```js
// helpers.js

/**
 * hbs helpers get invoked by rendering
 * a template. They get the res.locals as
 * context in `this`
 */
module.exports = function(app) {
  return {

    /**
     * a basic form helper to render input fields
     */
    input: function(field, opt) {
      opt = opt.data ? {} : JSON5.parse(opt);
      var value = this.formdata ? this.formdata[field] || '' : '';
      var hasError = this.formerror && this.formerror[field];
      var ErrorMsg = hasError ? '<span class="help-block">' +
        this.__(
          this.formerror[field].msg,
          this.__('field.' + field),
          this.formerror[field].value
        ) +
        '</span>' : '';

      return `
          <div class="form-group ${hasError? 'has-error':''}">
            <label for="${field}">${this.__(opt.label || 'field.' + field)}</label>
            <input type="${opt.type || 'text'}"
              class="form-control"
              id="${field}"
              name="${field}"
              value="${value}">
            ${ErrorMsg}
          </div>`;
    }
  }
};
```
 
so a view could read like so:

```html
    <form>

        {{{ input 'username' }}}
        {{{ input 'password' "{type: 'password'}" }}}

        {{> alerts/formerrors}}

        <div class="text-center">
            <button type="submit" class="btn btn-primary btn-block">{{__ 'Sign In' }}</button>
        </div>

    </form>
```
