### ISSUE TITLE
route translation

### ISSUE THREAD

**Issue by goowikns** [mashpie/i18n-node#239]
This is not an issue.

But is it possible to have the route names in a json file?

For example:
**en.json**

```
{
  "registration": "signup"
}
```

**fr.json**

```
{
  "registration": "registration"
}
```

and have something like:

```
app.get("/" + translatedRouteHere, function(...) {
  res.render('signup', {...});
})
```

**Comment by mashpie** [comment]
sure, see: https://github.com/mashpie/i18n-node#i18n__l

**Comment by goowikns** [comment]
So I tried implementing this but I seems to be having an issue here.

**These are my routes:**

```
router.get('/:locale(fr|nl)', function(req, res, next) {
  console.log(req.params.locale);
  req.setLocale(req, req.params.locale);
  res.render('pages/' + req.getLocale() + '/index', {menu: 'home', title: req.__('menu.home.title')});
});

/* GET termsandcondition page. */
router.get(i18n.__l('/:locale/menu.termsandcondition.url'), function(req, res, next) {
  res.render('pages/' + req.getLocale() + '/termsandcondition', {menu: 'termsandcondition', title: req.__('menu.termsandcondition.title')});
});

/* GET organisation page. */
router.get(i18n.__l('/:locale/menu.organisation.url'), function(req, res, next) {
  res.render('pages/' + req.getLocale() + '/organisation', {menu: 'organisation', title: req.__('menu.organisation.title')});
});
```

the index route ('/fr' or '/nl') works without problems. But for the other 2 I get a 404 status.

**nl.json:**

```
{
  "menu": {
    "home": {
      "item": "Home",
      "title": "Welkom",
      "url": ""
    },
    "termsandcondition": {
      "item": "Reglement",
      "title": "Reglement",
      "url": "reglement"
    },
    "organisation": {
      "item": "Organisatie",
      "title": "Organisatie",
      "url": "organisatie"
    }
  }
}
```

**fr.json:**

```
{
  "menu": {
    "home": {
      "item": "Home",
      "title": "Bienvenue",
      "url": ""
    },
    "termsandcondition": {
      "item": "Réglement",
      "title": "Réglement",
      "url": "reglement"
    },
    "organisation": {
      "item": "Organisation",
      "title": "Organisation",
      "url": "organisation"
    }
  }
}
```

**Comment by mashpie** [comment]
You should skip the Parameter in 
i18n.__l('/:locale/menu.termsandcondition.url')
As it is not included in your translations

> Am 22.05.2016 um 09:50 schrieb Peter Vercauteren <notifications@github.com>:
> 
> i18n.__l('/:locale/menu.termsandcondition.url'

**Comment by goowikns** [comment]
Offcourse :)

But what if I do wanted to include the param in my routes. I tried following:

```
/* GET termsandcondition page. */
router.get('/:locale/' + i18n.__l('menu.termsandcondition.url'), function(req, res, next) {
  req.setLocale(req, req.params.locale);
  res.render('pages/' + req.getLocale() + '/termsandcondition', {menu: 'termsandcondition', title: req.__('menu.termsandcondition.title')});
});

/* GET organisation page. */
router.get('/:locale/' + i18n.__l('menu.organisation.url'), function(req, res, next) {
  req.setLocale(req, req.params.locale);
  res.render('pages/' + req.getLocale() + '/organisation', {menu: 'organisation', title: req.__('menu.organisation.title')});
});
```

unfortunately it gives me a **404**.

Or do you suggest to set my **'menu.[item].url'** to **'/[lang]/[item]'**? Which offcourse is easier to assign to navigation items. 

I tried this too, but the problem is I need to set **'setLocale'**. But how do I retrieve the language then if my route params don't have any **:locale**?

**Comment by mashpie** [comment]
You could include your param "as is" in your locale key. I'll gist an example when back to desktop...

**Comment by mashpie** [comment]
Follow the example:

Keys in your json:
en.json --> /:locale/products/:id? 
es.json --> /:locale/productos/:id? 
app.get( __l('/:locale/products/:id?'), function (req, res) {  });
Matches URLs like
/en/products/123 or
/any/products/456
Plus you get en as params

Von meinem iPhone gesendet

**Comment by goowikns** [comment]
Oke but what value do you assign **"/:locale/products/"** to?

I have for example in **nl.json**: 

```
{
  "/:locale/termsandcondition": "/nl/reglement",
  "/:locale/organisation": "/nl/organisatie",
  "/:locale/documentation": "/nl/documentatie",
  "/:locale/registration": "/nl/registratie",
  "/:locale/login": "/nl/login"
}
```

**Comment by goowikns** [comment]
Okay, to simplify the coding as I have to finish the first part this evening :)

I removed the locale parameter and used a simple language switcher & cookie from:
#237 

Thanks again for your great support & amazing module :+1: 
Personally I don't need any help on this issue for now. But maybe for later it might be helpful for others.
