### ISSUE TITLE
Object notation instead of key=value pairs

### ISSUE THREAD

**Issue by gokaygurcan** [mashpie/i18n-node#240]
Hello,
I'm trying to separate the blocks logically, like homepage, about, account, etc. As an example: 

```js
{
  "homepage.header.tagline": "Something meaningful",
  "homepage.hero.button": "Click me",

  "account.login.username": "Enter your username",
  "account.login.password": "Enter your password",
  "account.logout.button": "Click here to log out"
}
```
and it goes like that.  Inside of my templates, I use them as `__('homepage.hero.button')` for instance. 

What I'd like to have is keeping the usage part in template as is and change the first part like this:

```js
{
  "homepage": {
    "header": {
      "tagline": "Something meaningful"
    },
    "hero": {
      "button": "Click me"
    }
  },
  "account": {
    "login": {
      "username": "Enter your username",
      "password": "Enter your password"
    },
    "logout": {
      "button": "Click here to log out"
    }
  }
}
```

This makes more sense in terms of separation perspective and easier to understand imho. 

I hope you'll consider this feature request, thanks in advance.

**Comment by mashpie** [comment]
this is implemented https://github.com/mashpie/i18n-node#object-notation

**Comment by gokaygurcan** [comment]
Wow. 
I guess I shouldn't open any ticket after 6 pm. It's clear that I'm becoming blind as a bat after some point. 

Thanks for pointing that out!

**Comment by mashpie** [comment]
no worries :)
