### ISSUE TITLE
setlocale doesn't change the language of the texts

### ISSUE THREAD

**Issue by hamedhemmati** [mashpie/i18n-node#246]
I am kind of new to node so I am not sure if I am doing this right but I have this in my route which is supposed to set the locale for the view.
`
var express = require('express');
var router = express.Router();
var i18n = require('i18n');

/* GET home page. */
router.get('/', function(req, res, next) {
  i18n.setLocale('de');
  var current_locale = i18n.getLocale();
  res.render('index', { title: 'Sayyal', test: current_locale });
});`

When I view the page the getLocale is returning de but the text is still in English. Now if I use URL parameter then it switches the text language.

Am I missing something here. I thought setLocale() would change the language without having to do URL parameters.

**Comment by mashpie** [comment]
pls refer to https://github.com/mashpie/i18n-node#i18nsetlocale
