### ISSUE TITLE
setlocale doesn't change the language of the texts

### ISSUE THREAD

**Issue by hamedhemmati** [mashpie/i18n-node#247]
I am kind of new to node so I am not sure if I am doing this right but I have this in my route which is supposed to set the locale for the view.

```
var express = require('express');
var router = express.Router();
var i18n = require('i18n');

router.get('/', function(req, res, next) {
  i18n.setLocale('de');
  var current_locale = i18n.getLocale();
  res.render('index', { title: 'Sayyal', test: current_locale });
})})
```

When I view the page the getLocale is returning de but the text is still in English. Now if I use URL parameter then it switches the text language.

Am I missing something here. I thought setLocale() would change the language without having to do URL parameters.

**Comment by rbaprado** [comment]
Same doubt here

**Comment by hamedhemmati** [comment]
OK so I can either do i18n.setLocale(res, 'de'); or res.setLocale('de') and that would change the text but the getLocale() comes back with the default language value not what I set earlier.

**Comment by mashpie** [comment]
please use both according to specs. https://github.com/mashpie/i18n-node#i18nsetlocale + https://github.com/mashpie/i18n-node#i18ngetcatalog 

You may find the example https://github.com/mashpie/i18n-node/tree/master/examples/express4-setLocale usefull or grap what suites from the test https://github.com/mashpie/i18n-node/blob/master/test/i18n.setLocale.js

**Comment by hamedhemmati** [comment]
I think I see what the problem is. I have been able to get it to work but I have to remove 'en' from my list of available locales or move down from being the first in the list.

This is also happening when I try to change the `defaultLocale `in the configuration. Since my browser is returning en in the header as long as en is the first in the list of locales then it ignores what the `defaultLocale `is and the `getLocale `always returns en. 

Is there a way to ignore what the browser header is returning? I can see this being a big issue for people that travel.

I am trying to set their language by either what I have set in the database for the users that are logged in or if not logged in then by their cookie not by their browser.

**Comment by mashpie** [comment]
Sry to have to say RTF my dear ;)

Yes, you can configure options for query-parameters and/or cookies, like (@see https://github.com/mashpie/i18n-node#list-of-all-configuration-options):

```js
i18n.configure({
    // setup some locales - other locales default to en silently
    locales:['en', 'de'],

    // fall back from Dutch to German
    fallbacks:{'nl': 'de'},

    // you may alter a site wide default locale
    defaultLocale: 'de',

    // sets a custom cookie name to parse locale settings from - defaults to NULL
    cookie: 'yourcookiename',

    // query parameter to switch locale (ie. /home?lang=ch) - defaults to NULL
    queryParameter: 'lang'
});
```

> The locale itself is gathered directly from the browser by header, cookie or query parameter depending on your setup.

> In case of cookie you will also need to enable cookies for your application. For express this done by adding app.use(express.cookieParser())). Now use the same cookie name when setting it in the user preferred language, like here:

```js
res.cookie('yourcookiename', 'de', { maxAge: 900000, httpOnly: true });
```

> After this and until the cookie expires, i18n.init() will get the value of the cookie to set that language instead of default for every page.

So do give an example, consider this:

```js
i18n.configure({
  locales: ['nl', 'fr'],
  cookie: 'gmlang',
  queryParameter: 'lang', // query parameter to switch locale (ie. /home?lang=nl) - defaults to NULL
  directory: __dirname + '/locales',
  defaultLocale: 'nl'
});

app.use(i18n.init);

app.get('/home', function(req, res, next){

  /**
   * req.__() will lookup 'Hello World' and add it if missing
   * or return it's translated string form a locale file named
   * nl.json or fr.json.
   *
   * i18n.init takes care of setting locale according to cookie 
   * and query parameter in precedence of:
   *
   * 1. HTTP-Headers, fallback to
   * 2. cookie, fallback to
   * 3. query
   *
   * that way you might for exampple overwrite any language cookie 
   * with a query parameter.
   */

  res.send('<body>' + req.__('Hello World') + '</body>');
});
```

- a request for  `/home` will default to `nl`
- a request for `/home?lang=fr` will use `fr`for that single request
- consider setting the cookie via middleware tp persist that switch

**Comment by hamedhemmati** [comment]
Sorry I think I didn't make myself very clear. I have everything working fine now both with browser parameter and cookies. The problem I am seeing is that the defaultLocal is kind of useless here. 

The first time a user gets to the site they don't have their cookie set and they may not use a browser parameter to get to the site which is when you rely on the defaultLocal to make sure the site is always displayed in a certain language when the user hasn't had a selection yet but since i18n can also setLocale based on the browser header then the defaultLocale becomes useless because browsers always have a locale setting.

Now this is not an issue in 90% of the cases but then there are the 10% that are traveling users or are using VPN to connect then their browser header may not have the correct locale settings. Mine was giving me wrong information because I had my anonymizer running and it kept showing wrong locales. I think there should be an option to disable the browser header as a way to set the locale.

**Comment by mashpie** [comment]
well ok, two points here:

1) defaultLocale is used as last possible fallback option in case i18n can't find any supported (settings `locales: []`) by either header, cookie or query. If ommited i18n has a hardcoded default of 'en' as very last resort.

2) to disable header check, set a cookie if cookie is missing on 1st request and redirect. This way you also determine if cookies are supported by that client.

2b) you could also just set that header to null (or any desired default) right before i18n.init so i18n won't be able to guess a language setting

Both 2) options are quick workarounds for now, though.

I agree that a switch for opting-out header checks should get added sooner which git discussed in #216 and will be available in 0.9.0 which will need to wait until some refactories are completed

**Comment by arathipanya** [comment]
I use 18n.setLocale(locale) to translate text in controllers and use i18n.setLocale(req, locale) to translate text in partials. I don't know why but I have to use it this way.

**Comment by mashpie** [comment]
@arathipanya - you should use `app.use(i18n.init)` and `req.__()`.Another example https://github.com/mashpie/i18n-express-hbs-prefix

`setLocale` is to implement any custom business logic. There 2 usage modes: 

- global (`18n.setLocale(locale)`) singleton, shared
- scoped (`i18n.setLocale(req, locale)`) singleton or instance, but alway in context of `req`
