### ISSUE TITLE
Translating a date results in bad output

### ISSUE THREAD

**Issue by jim-y** [mashpie/i18n-node#248]
My problem is quite simple, the example demonstrates it.

```javascript
console.log(totpExpiration); // 6/24/2016, 1:01:46 PM
const body = __('SMS_BODY_TEXT', { totp, totpExpiration });
console.log(body); // The code expires at 6&#x2F;24&#x2F;2016, 1:01:46 PM
```

Now the "/" characters become "&#x2F;" HTML Entity and I did not find anything about escaping my variables for __(). Mind that there is no templating engine here, I will send the string out in SMS.

**Comment by mashpie** [comment]
i18n doesn't do any html escaping/sanitizing by itself all. And I assume console.log didn't start either. Please check your .json files. And check the docs of your template engine. 100% of escaping issues were related to the template engine used. See example for hbs:

> Handlebars HTML-escapes values returned by a {{expression}}. If you don't want Handlebars to escape a value, use the "triple-stash", {{{.

Same logik applies to mustache (https://mustache.github.io/mustache.5.html):

> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

How does the 'SMS_BODY_TEXT' translation look like? I bet its like

```json
{
  "SMS_BODY_TEXT": "The code expires at {{totp}}"
}
```

but should read

```json
{
  "SMS_BODY_TEXT": "The code expires at {{{totp}}}"
}
```

...that's what mustashe support means: It's just mustache. Am I right?

**Comment by jim-y** [comment]
Hi @mashpie,

Thanks for the fast answer, you got it right, my template looks like: `"SMS_BODY_TEXT": "Code: {{totp}}. This is a one time verification code sent to you by Company. The code expires at {{totpExpiration}}"` While we use handlebars for emails, we do not use it for SMS. The whole process (simplified) looks like:

```javascript
const i18n = require('i18n');
i18n.configure({
            locales: ['en'],
            directory: `${__dirname}/../../locales`
});
const totpExpiration = '' + new Date(params.totpExpiration).toLocaleString();
console.log(totpExpiration); // 6/24/2016, 1:01:46 PM
const body = i18n.__('SMS_BODY_TEXT', { totp, totpExpiration });
console.log(body); // The code expires at 6&#x2F;24&#x2F;2016, 1:01:46 PM
```

Now I don't see anything but i18n in this. We will send this out after this, and even we won't use handlebars at all, nor any other templating engine. Should I change `{{}}` in the templates to something other?

**Comment by mashpie** [comment]
it helped because mustache escapes to entities by default. Using `{{{}}}` gives the plain origin instead.

**Comment by klemensz** [comment]
Ran into the same issue. Would be nice 🙂 if this was mentioned in the readme. Somebody that uses i18n-node does not necessarily know about mustache (like me).

**Comment by OlivierChirouze** [comment]
It's great to learn there is a simple solution to this issue, but it would be even better to mention it in the readme ;-)
Thanks
