### ISSUE TITLE
Translating strings without req/res object

### ISSUE THREAD

**Issue by axelfran** [mashpie/i18n-node#250]
Hi,

I use i18n for translation on my backend web server, and I'm having some issues regarding translating strings that are not related to the user initiating the request. A typical use case is when user 1 (the one sending a request to the backend service) likes a photo, and I should send a localised push message to the publisher of the photo (user 2). 

I'm storing all users' preferred locale in my database (received from i18n.getLocale()), so I've ensured access to it. My problem seems to be that I don't have access to i18n from my push controller, as the req/res objects are not available here. 

My solution this far is as follows: 

```
var i18n = require('i18n');

i18n.configure({
    directory: __dirname + '/../locales'
});

function viewsAlert(username, title, views) {
  userController.getLocale(null, username, function(err, locale) {
    i18n.setLocale(locale);
    var message = i18n.__({phrase: "PUSH_VIEWS", locale: "en"});
    console.log(message);
```

However this doesn't work, and log output is:
`undefined`

Do anyone have any suggestions for how I can use stored locales to send localised push messages with i18n?

Many thanks!

**Comment by mashpie** [comment]
is this your complete code? I am missing any locales defined in `i18n.configure`.

```js
i18n.__({phrase: "PUSH_VIEWS", locale: "en"});
````

should always return the `en` translation. You should not need to use `i18n.setLocale(locale);` in that case.

**Comment by axelfran** [comment]
Yes, it is (in this fie, at least - pushController.js). I thought it would automatically fetch languages from the files in the /languages folder? E.g. en.json and no.json? 

What happens now is actually that all values in en.json are removed on the first run of the code, and then PUSH_VIEWS are filled in as both a key and value on the second run (and also printed on the console). Interestingly the same happens If I change "locale: "en"" to "locale:"no"".

In app.js I do the following:

```
i18n.configure({
    directory: __dirname + '/locales'
});

app.use(i18n.init);
```

**Comment by mashpie** [comment]
sounds like your initial json files have a syntax error. Could you check (or post) those?

**Comment by axelfran** [comment]
OMG, you are totally correct that there was an error in the JSON files. What a stupid mistake, but thanks a lot for helping out!

**Comment by mashpie** [comment]
no worries :) I will add a syntax check in one of next releases
