### ISSUE TITLE
How to use i18n in a CLI style app with a dependency that uses i18n? Currently loosing dependent modules messages.

### ISSUE THREAD

**Issue by chambrid** [mashpie/i18n-node#251]
We depend on a library module (in our package.json) that also translates messages using i18n. In this library module they set the following:

```
var i18n = require('i18n');
i18n.configure({
    directory: __dirname + '/../messages',
    defaultLocale: 'en',
    updateFiles: false
});
```

In our applications script file we do a similar setup. As a result it seems like our `i18n.configure()` overrides our dependencies setup and the only way we can get messages is to include all the messages from our dependent module in our application. Is this expected? Is there a way we can work around this in either the library or main application?

**Comment by mashpie** [comment]
using the `register` option should help. Inspiration in https://github.com/mashpie/i18n-node/blob/master/test/i18n.configureRegister.js

**Comment by chambrid** [comment]
I've tried using register without any luck. It looks like every time you do configure it resets the locales object: https://github.com/mashpie/i18n-node/blob/master/i18n.js#L74

I tried your suggestion above with the following as a simple test case:

**package.json:**
```
{
  "name": "i18n-test",
  "version": "0.0.11",
  "description": "A test of i18n configure.",
  "author": "chambrid",
  "license": "MIT",
  "engines": {
    "node": ">= 4.2.0"
  },
  "dependencies": {
    "i18n": "^0.8.3"
  }
}
```
**app.js:**
```
const i18nMessages = require("i18n");
const i18nErrors = require("i18n");

var messages = {};
i18nMessages.configure({
	updateFiles: false,
        directory: __dirname + '/messages',
	defaultLocale: 'en',
        register: messages
});

var errors = {};
i18nErrors.configure({
	updateFiles: false,
        directory: __dirname + '/errors',
	defaultLocale: 'en',
        register: errors
});

console.log(messages.__('app.list.field.disk'));
console.log(errors.__('conversation.try.again.yes.no'));
```
**errors/en.json:**
```
{
	"conversation.timed.out": "Our conversation timed out.  You can try again later.",
	"conversation.try.again.or.exit": "That is not one of the choices. Try again, or type 'exit'.",
	"conversation.try.again.yes.no": "That is not one of the choices. Try *yes* or *no*."
}
```

**messages/en.json:**
```
{
"app.list.field.bound.services": "Bound Services",
"app.list.field.disk": "Disk"
}
```

> run `npm install`  && `node app.js`

I only get 
>$ node app.js
>app.list.field.disk
>That is not one of the choices. Try *yes* or *no*.

If I comment out the configure for errors I will get:
>$ node app.js
>Disk

**Comment by mashpie** [comment]
ok, this needs further investigation...

**Comment by chambrid** [comment]
Thanks!

**Comment by mashpie** [comment]
I never had to setup such and used one single file per language for all translations. There are requests for support of namespaces and concatenation of multiple files.

**Comment by chambrid** [comment]
I'm using a library module that externalizes & translates strings that is common to several apps that also use i18n. It would be nice if the `locales` object could somehow be tied to the registered object. This may be similar to the namespace or scoping requests. Concatenating files wouldn't help me since the configure exists in the app and the library module (and the library modules translations are lost unless I include them in my apps locale files.

**Comment by veeramarni** [comment]
I agree with @chambrid We want our libraries to use i18n individually and not get overwritten by the project which loads the library.

**Comment by romitamgai** [comment]
Any progress on this @mashpie ? Still not able to provide multiple configurations to i18n.

**Comment by mashpie** [comment]
#323 or #329 - still need to get reviewed. And still my time is far too limited atm :(

**Comment by woodcockjosh** [comment]
@mashpie maybe you can add an owner to the repo to get some of these things resolved. i18n is a great library. I'm happy to volunteer

**Comment by mashpie** [comment]
both merged... issue dangled - closing to cleanup. comment in case :)
