### ISSUE TITLE
Problem with select object in object

### ISSUE THREAD

**Issue by Mojo90** [mashpie/i18n-node#259]
I have a menu-object in my json-File that has a menu object:
```
"menu": {
    "blog": {
	    "name": "Blog",
	    "href": "/blog"
    }
}
```
Now if I want to select the name like this: `res.__('menu.blog.name')` it does print out menu.blog.name thus I think it does not find the object. But if I print out console.dir(res.__('menu')) it does print out the blog-object. Very weird? Cause you state here: [https://github.com/mashpie/i18n-node#defaults](url) that it should work like this. Any hints? Thx!

**Comment by mashpie** [comment]
you probalbly missed to turn on object notation:

```js
i18n.configure({
    // [...]

    // enable object notation
    objectNotation: true,

    // [...]
});
```

**Comment by Mojo90** [comment]
cool, thx a lot works like a charm now :-)!
Just started with i18n-node and missed that config, sorry...

**Comment by mashpie** [comment]
also check the output of 

```js
res.getLocale();
```

it should match you desired locale file, ie:

```
"en" => en.json
```

**Comment by mashpie** [comment]
cool, glad to helped
