### ISSUE TITLE
require JSON instead of reading from FS

### ISSUE THREAD

**Issue by TakanashiOuken** [mashpie/i18n-node#262]
Would be nice if can let i18n to read a a imported json and not use the directory.
Then I can webpack it.....

**Comment by no-more** [comment]
Hello, any news about this ? 

I need to bundle my apps with webpack and currently I can't due to dynamic imports in this plugin. Do you think it would be possible to implement that ? 

@TakanashiOuken did you find a solution ?

Thanks a lot.

**Comment by BostjanPisler** [comment]
Did anyone try to copy the locales folder with webpack and read from there? Could probably work, will investigate.
