### ISSUE TITLE
Encoding of strings with Mustache syntax

### ISSUE THREAD

**Issue by axelfran** [mashpie/i18n-node#265]
Hi,

When translating a string with the mustache syntax escape characters are encoded in hex(?) format, and I'm not able to convert them back. Ideally they should not be converted at all, but do anyone have suggestions to how they can be converted back?

Example: 
```

var title = "Thing with / in it";
var price = 100;

var message = i18n.__("NOTIFICATION", {
                title: title,
                price: price
            });

console.log(message);
```
In this case output is:  `Thing with &#x2F; in it`, and the question is then how I can best convert &#x2F; back to a slash, or just not convert it at all. 

Appreciate any input!

**Comment by mashpie** [comment]
Can't find any mustache expression in your example. My guess would be to use {{{}}} instead of {{}} to keep mustache from escaping.

**Comment by axelfran** [comment]
You are totally right. In my hurry of creating an example I forgot the notification String, and you are right that I used `The title is: {{title}}` with two brackets instead of three. The issue was solved by using three.

Many thanks!
