### ISSUE TITLE
Recommended encoding

### ISSUE THREAD

**Issue by Aides359** [mashpie/i18n-node#267]
What is the recommended encoding for the translation JSON files?

The automatically generated files had (at least according to VS2015) "Western European (Windows) - Codepage 1252" which caused German Umlauts to not display correctly.

Changing the encoding to "UTF-8 without BOM" fixed this.

**Comment by mashpie** [comment]
i18n doesn't take encoding into account. Thus, any given encoding of your strings get passed to json files as is. I'd highly recommend using utf8.

**Comment by Aides359** [comment]
Okay, in that case it was the problematic default encoding from VS.
Thanks 👍
