### ISSUE TITLE
v0.10 and v0.12 support?

### ISSUE THREAD

**Issue by travnels** [mashpie/i18n-node#285]
We just went into end of life for Node v0.10 (2016-10-31) and v0.12 is right around the corner in December (https://github.com/nodejs/LTS). Is removing support for these versions on the release schedule?

**Comment by mashpie** [comment]
Yes, next Release will 1st drop travis Test and will run Legecy-Tests locally for a while. Will Post MORE details....

**Comment by travnels** [comment]
I think we can keep the travis tests, but drop:
https://github.com/mashpie/i18n-node/blob/master/.travis.yml#L3-L5
and
https://github.com/mashpie/i18n-node/blob/master/.travis.yml#L8
