### ISSUE TITLE
setLocale in express 4 with no cookies

### ISSUE THREAD

**Issue by telekosmos** [mashpie/i18n-node#290]
Hi
I want to set the locale for every request based on the `x-locale` request header. So in the API middleware, I check for the `x-locale` and, if it exists, I do `i18n.setLocale(x_locale_header_value)`. But just after doing that, I call `i18n.getLocale()` and I always get the default locale (en in this case). 

This is necessary for me as I use (just once throughout the API) a handlebars template which is always translated to the same language: default locale 'en'.

To be honest, I don't know whether or not I am doing something wrong and/or missing something. I've checked the `i18n.init` method documentation and issues but I don't use cookies or param language at all, so it doesn't have effect on the API.

So, any hint is welcome :-)

Cheers!!

**Comment by telekosmos** [comment]
Sorry, I forgot... This is the configuration when the API starts:
```javascript
i18n.configure({
    locales:['en', 'es'],
    defaultLocale: 'en',
    // watch for changes in json files to reload locale on updates - defaults to false
    autoReload: true,
    updateFiles: false,
    directory: __dirname + '/../translations'
});
```

And in the middleware, the code to (try to) set a new locale (if necessary) for every request is:
```javascript
// Only if x-locale is set try to change the api locale
if (req.headers["x-locale"]) {
    var locale  = req.headers["x-locale"];

    //set locale check if locale is correct and save only if it's truth
    i18n.setLocale(locale);
}
```

Cheers again

**Comment by mashpie** [comment]
please review example usage in

- https://github.com/mashpie/i18n-node#some-words-on-register-option and
- https://github.com/mashpie/i18n-node#i18nsetlocale

setting locale like so:

```js
i18n.setLocale(req, locale);
```

should work. Beware that setLocale applies`x-locale`-values of 'en' or 'es' in your setup. Any other value will default to 'en'

**Comment by telekosmos** [comment]
Hi
Thanks for the quick reply. Actually I spent time trying things and now is working with no huge changes on the code I provided... So don't pay (so much) attention to the second comment ☺️ 

Regarding to your answer, may I use `i18n.__('sting_to_translate')` in any part of the express app after doing `i18n.setLocale(req, locale)`?

I don't understand quite well your last comment regarding the setup (=> I dunno whether or not I'm doing something 'no well'). The code seems to be working for back to back requests in different locales...

Thanks again!!!

**Comment by mashpie** [comment]
`i18n.__('sting_to_translate')` dispatches from __global__ object. Doing so will lead to concurrency issues while binding to `req` sticks it's locale setting to that single request only, which is the only way to ensure correct translations for each and every request handled. 

So I strongly advise __local__ usage like so: 

```js
i18n.setLocale(req, locale) // sets all of req, res and res.locals

// [...]

req.__('sting_to_translate') // or
res.__('sting_to_translate') // or
res.locals.__('sting_to_translate')
```
