### ISSUE TITLE
Vertical bar character exclude previous text

### ISSUE THREAD

**Issue by giacomocerquone** [mashpie/i18n-node#309]
Hello everyone, this is a great project, thank you.
I was noticing that putting something like this in my json file:
`Title | Subtitle`
Will truncate this part: `Title |` and ejs (I'm using it as a expressjs middleware with ejs as a template engine and everything works fine) get only `Subtitle` (tried to parse it with <% %> <%- %> <%= %>).

I have really an enormous amount of work to do and I don't think I'll be able to investigate further for now, hope you'll take a look to it!
Thank you again 😄

**Comment by mashpie** [comment]
The pipe `|` is used to declare intervals in plurals. see #274 for reference.

Currently the only work around is using `&#124;` instead of `|`

**Comment by hugodes** [comment]
Using &#124; just prints &#124; for us

**Comment by mashpie** [comment]
Closing. Workaround #370 should be clarified in docs though.
