### ISSUE TITLE
Some strings don't load with no message or no reason

### ISSUE THREAD

**Issue by provector** [mashpie/i18n-node#313]
As in description some strings just don't simply load:

Event List <-- OK [event_list]
Hello World! <-- OK [msg_test]
[msg_test2] <--- doesn't work
Hello World! <-- OK
WEATHER <-- OK

There's no error thrown while parsing json, file has about 500 entries, I noticed like 5% of them don't work, if I add new entry to file it dosn't read in some places in my code, in other it does. Everywhere I use standard method and in the same way there's no fancy stuff going on. After 4 hours of debugging my code and all I gave up, it is so frustrating.

**Comment by mashpie** [comment]
could pls provide some more infos, like node version, initialization sequence, example files?

i18n loads the whole json file once at start. Reading a partial file results in json-parsing exceptions. So we need to take a closer look into your implementation details.

**Comment by provector** [comment]
My apologies, its very embarrassing, but after long and exhausting debugging I found the issue in my code... Module seems to work perfectly. Again sorry for jumping straight here but it was long friday back then.

**Comment by mashpie** [comment]
Glad to hear... no worries, we all know those fridays and some early saturdays too ;)
