### ISSUE TITLE
Uncaught TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by Ts-alan** [mashpie/i18n-node#315]
I have next error 
**Uncaught TypeError: fs.existsSync is not a function**
 in package after code

	let i18n = require("i18n");

	i18n.configure({
		locales: ['en'],
		directory: __dirname + '/assets/localization'
	});
I  insert this code in typescript

**Comment by MeikelLP** [comment]
@Ts-alan Why was this closed? What is the fix? I'm having the same issue.
