### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by steeply** [mashpie/i18n-node#325]
```
➜  test git:(master) ✗ npm i  i18n --save

> typechecker@2.0.8 preinstall /Applications/MAMP/htdocs/test/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js

npm ERR! Cannot read property 'pause' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steeply/.npm/_logs/2017-08-28T08_06_17_854Z-debug.log

➜  test git:(master) ✗ node -v && npm -v
v8.4.0
5.4.0

```

**Comment by fmasclef** [comment]
@steeply until dependencies are updated, you should downgrade to 5.**3**.0.
`npm i -g npm@5.3.0` should do the trick.

**Comment by mashpie** [comment]
while installing node 8.4 via nvm it sticks to npm 5.3:

```
➜  i18n-testings nvm install 8.4
######################################################################## 100,0%
Computing checksum with shasum -a 256
Checksums matched!
Now using node v8.4.0 (npm v5.3.0)
```

and installs just fine on an empty project:

```
➜  i18n-testings npm i i18n -S

> typechecker@2.0.8 preinstall /Users/marcus/Sites/i18n-testings/node_modules/extendr/node_modules/typechecker
> node ./cyclic.js


> typechecker@2.0.8 preinstall /Users/marcus/Sites/i18n-testings/node_modules/extract-opts/node_modules/typechecker
> node ./cyclic.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN i18n-testings@1.0.0 No description
npm WARN i18n-testings@1.0.0 No repository field.

+ i18n@0.8.3
added 41 packages in 5.258s
```

extendr is dependency of watchr in older messageformat :(

```
➜  i18n-testings npm list extendr
i18n-testings@1.0.0 /Users/marcus/Sites/i18n-testings
└─┬ i18n@0.8.3
  └─┬ messageformat@0.3.1
    └─┬ watchr@2.4.13
      └── extendr@2.1.0 
```

**Comment by fmasclef** [comment]
Correct. npm 5.**4**.0 comes with `npm update -g`. I guess @steeply issued that command. Reverting to 5.**3**.0 that comes with official node 8.4.0 package solves the issue.

@mashpie: it seems that using messageformat 1.0.2 would prevent npm 5.**4**.0 to fail during installation. Is there any option to test this version?

**Comment by mashpie** [comment]
I am about to update all deps and also drop some support for legacy node versions - but 1st some PRs need to get merged

**Comment by fmasclef** [comment]
Excellent. To me, this bug can be closed. @steeply your point?

**Comment by steeply** [comment]
@fmasclef 
On npm 5.3.0 it works.
But I would like to support new versions.
The question can be closed.
Thank you!

**Comment by HollyPony** [comment]
In addition, this issue can be solved upgrading the `messageformat` dependency to 1.0.0 since it is a complete rework : https://github.com/messageformat/messageformat.js/releases .

**Comment by steeply** [comment]
There are some moves to fix the situation with the latest versions of npm?

**Comment by HollyPony** [comment]
The issue still happen on npm@5.4.2 so ... we use npm@5.3.0 ...

**Comment by boutell** [comment]
This is a dealbreaker for our users. Is there any workaround that doesn't involve telling them to install an old version of npm?

**Comment by boutell** [comment]
I get that this is npm's bug, not yours. I can "npm install" version 0.3.1 by itself with newer npm, but I can't npm install it as a dependency of something else. Weird.

**Comment by boutell** [comment]
This is fixed in npm 5.5.x, which will become npm "latest" soonish, at which point this complaint will hopefully stop recurring:

```
# this is happy
rm -rf node_modules/* && npm install npm@5.3 && ./node_modules/.bin/npm install
# this is sad
rm -rf node_modules/* && npm install npm@5.4 && ./node_modules/.bin/npm install
# this is happy again
rm -rf node_modules/* && npm install npm@5.5 && ./node_modules/.bin/npm install
```

So you can `npm install -g npm@5.5`, or `npm install -g npm@5.3` if you'd rather not live on the edge.

I think this should be considered closed, perhaps you'd like to post a warning about npm 5.4 as we're doing.

**Comment by balupton** [comment]
Owner of typechecker, extract-opts, watchr here - all our deps are updated, and have been for about a year or so. messageformat, not owned by me, has also been updated

As such, I concur with the above messages, that solution is updating messageformat dependency to 1.0.0

**Comment by HollyPony** [comment]
That’s the point of my pull request :)

**Comment by cartuchogl** [comment]
Node 8.8.1 bundle 5.4.2. The workaround that I work for me is:
````json
"i18n": "HollyPony/i18n-node#upgrade-messageformat",
````
in my package.json. In think that is not perfect solution, but works ;)
