### ISSUE TITLE
Request: Multiple responses for the same phrase

### ISSUE THREAD

**Issue by magnusburton** [mashpie/i18n-node#326]
I'd like to suggest a way to include multiple responses to the same phrase. These'd be picked at random when requested and returned.

    "greeting": {
        "formal": [
            "Hello"
        ],
        "informal": [
            "Hi",
            "Howdy",
            "Hey"
        ]
    }

And whenever you request `__('greeting.informal')` you would get either `Hi`, `Howdy`, or `Hey` in return.

**Comment by bickerdyke** [comment]
That would be a great extension that could make it easy to create more natural conversations.

For now, I am using a crude workaround taking advantage of i18n returning a whole array (if no moustache {{}} syntax is present), picks a random element and performs some almost-moustache replacement.

`function i18nPick(text:string, args:i18n.Replacements)
{
  let i18nReturn = i18n.__(text);
  
  if (Array.isArray(i18nReturn)) {
    const randomElement = Math.floor(Math.random() * (i18nReturn.length));
    i18nReturn = i18nReturn[randomElement];
  }

  return i18nReturn.replace(/{(\w+)}/ig, function(match:string) {
    return args[match] || match;
 });
}`

` i18nPick("name.recall", {"{name}": String(givenName), "{verb}": String((i18n.__("verb."+doWhat))) })`

`	"name": {
		"recall": [
			"Of course {name}!",
			"{name} would {verb} that.",
			"{name}!"
		]
	}`


Yes... anything but elegant... Would be nice to see see that isArray() return[random] logic built in transparently.

**Comment by mashpie** [comment]
this is more a speach processing than translating issue - while nice it's out of scope of this module. At scale I had good experience with https://www.textengine.io/ :)

but to leave 2cents on it - for readability and performance (split vs regex) I'd refactor above to:

```json
{
  "greeting": {
      "formal": "Hello",
      "informal": "Hi,Howdy,Hey"
  }
}
```

```js
// return one sample entry from array
const sample = list => list[Math.floor(Math.random() * list.length)];

// parse to array and return sample
const rand = phrase => sample(phrase.split(','))

rand(i18n.__('greeting.informal')) // --> Howdy
rand(i18n.__('greeting.informal')) // --> Hi
rand(i18n.__('greeting.informal')) // --> Hey

i18n.__('greeting.formal') // --> Hello

// even works like

rand(i18n.__('greeting.formal')) // --> Hello
rand(i18n.__('greeting.formal')) // --> Hello
rand(i18n.__('greeting.formal')) // --> Hello

rand(i18n.__('greeting.informal')) // --> Howdy
rand(i18n.__('greeting.informal')) // --> Hi
rand(i18n.__('greeting.informal')) // --> Hey
```
