### ISSUE TITLE
Fallback translation

### ISSUE THREAD

**Issue by corradio** [mashpie/i18n-node#328]
Hi,

When a *translation* is missing from one language, it would be nice to be able to get it from a default language as fallback, instead of writing the translation key. Maybe we could use the fallback language as reference?
This would make it easier to have "in-progress" translations in production.

Olivier

**Comment by mashpie** [comment]
for reference: @see retryInDefaultLocale at https://github.com/mashpie/i18n-node#list-of-all-configuration-options
