### ISSUE TITLE
Throw an error / emit an error when unknown key is used?

### ISSUE THREAD

**Issue by evantahler** [mashpie/i18n-node#333]
Hi!

How can I get a log message / event / callback when an unknown key is attempted to be translated?  The normal behavior of simply returning the value is usually OK when requesting full strings to be translated, but with object notation, it is quite strange.

I imagine registering a callback as part of configure `onMissingKey()` would be very helpful to catch missing translations in a test suite.

**Comment by einfallstoll** [comment]
I double that. I'd like to have a configurable callback `onMissingKey`, one could throw/log an error, return a better translation (e.g. instead of 'obj.key.something' return 'Something') or return a generic error string for CI which is easy to detect (e.g. "[MISSING LOCALIZATION]").

**Comment by einfallstoll** [comment]
@mashpie I thought on adding a `missingKeyFn` option and then alter the value in the function returned by the `localeMutator`.
