### ISSUE TITLE
Saving language to cookie after visiting a page with the queryParametr

### ISSUE THREAD

**Issue by ShGKme** [mashpie/i18n-node#335]
Hello.
I configureted:
```
queryParameter: 'lang',
cookie: 'lang',
```
and wrote
```
app.use(cookieParser());
app.use(i18n.init);
```
So, after I visited .....?lang=en, the page is shown in English. But then, if I visited any other page without `queryParameter` I would have seen the page in my local language. Nothing saved to cookie.
I'm using the following code to fix it, but it looks like either I do something wrong or there is a bug.
```
app.use(function(req, res, next) {
    res.cookie('lang', req.getLocale());
    next();
});
```

**Comment by mashpie** [comment]
nothing wrong. perfectly solved. i18n is _reading_ cookies _not setting_ them. It is up to you how and where and when the cookie get's set. could be even in frontend within an SPA or during redirect response from a corporate sso provider and such ;)
