### ISSUE TITLE
Register global does not work on middleware in routes

### ISSUE THREAD

**Issue by carvalhoviniciusluiz** [mashpie/i18n-node#339]
Hi,
I make the setup
```
import i18n from 'i18n'

i18n.configure({
  register: global,
  locales:['en-US'],
  defaultLocale: 'en-US',
  directory: __dirname + '/locales',
  api: {
    '__': 't'
  },
  updateFiles: false
})

module.exports = i18n
```
I have also a middleware with
```
console.log(t('server.errors.404'))
```
it's a route
```
import middleware from '../middleware'
router.post('/', middleware, controller.anything)
```
my file en-US
```
{
  "server.errors.404": "Not found"
}
```
When I run, it returns undefined
Where is my mistake?

**Comment by vmjames** [comment]
I also had this problem but in fact it was due to my json file having a comma missing! When I had the default "updateFiles: true" it kept updating my language json file and I couldn't understand why. I guess it could not make sense of my json file so it was updating it thinking it was empty.

**Comment by mashpie** [comment]
register "global" means `global` as of https://nodejs.org/api/globals.html#globals_global

middleware normally act on local or request based context. Most common in express'isch `app.use((req, res, next) => next())` signatures... like: `i18n.init()` or in short: use something like

```js
app.use(i18n.init)
```

before heading the req over to your middleware. And within it use

```js
req.t('bla.bla.bla')
```
