### ISSUE TITLE
i need a string like 'youtube | Youtube' but i got 'Youtube' only 

### ISSUE THREAD

**Issue by lihxhit** [mashpie/i18n-node#340]
Depending on the ranged interval support,
if i need a string with '|' like 'youtube | Youtube' but i  only got 'Youtube'  instead.
What should i do then?

**Comment by mashpie** [comment]
use a unicode representation instead, ie. `"\007C"` 

https://www.toptal.com/designers/htmlarrows/punctuation/vertical-bar/
