### ISSUE TITLE
Quick usage question: What is the best way to ignore the language cookie when user is logged in their account?

### ISSUE THREAD

**Issue by aguyinmontreal** [mashpie/i18n-node#342]
When user is logged in in his account, I want i18n to ignore the cookie, and only display the page in user's account language.

**What is the best, easiest may to `res.render` a page in a specific language (other than the one of the cookie)?**

I'm a little bit lost in the documentation.

Thanks!

**Comment by mashpie** [comment]
Option 1) setup different `I18n` instances, with an without cookie for those routes (but you need somehow implement setLocale)

Option 2) use a query param to temporarily overwrite the given cookie value for a specific request

Option 3) use `i18n.setLocale(req, <locale>)` on those routes you want to customise
