### ISSUE TITLE
Cannot find module cyclic.js on npm install

### ISSUE THREAD

**Issue by Havock94** [mashpie/i18n-node#349]
Hello! I'm facing this issue when I try to install i18n from npm.
npm version is 5.3.0.
I installed typechecker (v4.4.1) before installing i18n but the same error appears (and it looks like it's trying to install typechecker@2.0.8 even if I have a newer version installed). Any hint?

> sudo npm install i18n --save
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
> 
> > typechecker@2.0.8 preinstall /volume1/web/mysite/node_modules/extendr/node_modules/typechecker
> > node ./cyclic.js
> 
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module '/volume1/web/mysite/node_modules/extendr/node_modules/typechecker/cyclic.js'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:575:3
> 
> > typechecker@2.0.8 preinstall /volume1/web/mysite/node_modules/extract-opts/node_modules/typechecker
> > node ./cyclic.js
> 
> 
> module.js:487
>     throw err;
>     ^
> 
> Error: Cannot find module '/volume1/web/mysite/node_modules/extract-opts/node_modules/typechecker/cyclic.js'
>     at Function.Module._resolveFilename (module.js:485:15)
>     at Function.Module._load (module.js:437:25)
>     at Function.Module.runMain (module.js:605:10)
>     at startup (bootstrap_node.js:158:16)
>     at bootstrap_node.js:575:3
> npm WARN mysite@1.0.0 No repository field.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! typechecker@2.0.8 preinstall: `node ./cyclic.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the typechecker@2.0.8 preinstall script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2018-01-12T07_34_17_706Z-debug.log`

**Comment by Havock94** [comment]
If it can help you, the error log says my ideal npm tree is this, and typechecker@2.0.8 appears as dependency of both extendr and extract-opts.

`├─┬ i18n@0.8.3`
`│ ├── async@1.5.2`
`│ ├── eachr@2.0.4`
`│ ├─┬ extendr@2.1.0`
`│ │ └── typechecker@2.0.8`
`│ ├─┬ extract-opts@2.2.0`
`│ │ └── typechecker@2.0.8`
`│ ├── glob@6.0.4`
`│ ├── make-plural@3.0.6`
`│ ├── messageformat@0.3.1`
`│ ├── safefs@3.2.2`
`│ ├── taskgroup@4.3.1`
`│ ├── typechecker@2.1.0`
`│ └── watchr@2.4.13`

**Comment by mashpie** [comment]
maybe a transitive dependency... i18n itself is written in plain js. no coffeescript, no typescript. Looking at your output it seams like `./cyclic.js`is a preinstall script run by `typechecker`which itself is a dependency of `extract-opts` which is not a dependency of `i18n`:

```sh
❯ npm list extract-opts
i18n@0.13.3 /Users/.../i18n-node
└── (empty)
```

closing. Please comment if there is something else.
