### ISSUE TITLE
I am using i18n for my FB chatbot interface , but when one user changes interface language it effect to other user , how can i make the module independent for each user ?

### ISSUE THREAD

**Issue by Abgaryan** [mashpie/i18n-node#350]

**Comment by PassTheMayo** [comment]
Can you please give us more information? If you're using Express, make sure it's properly setting the cookie value.

**Comment by Abgaryan** [comment]
No, i am not setting cookie values, I am using  botkit library [Example here ](https://github.com/howdyai/botkit/blob/master/examples/facebook_bot.js)

**Comment by tibibo** [comment]
Try to use  
`i18n.__({ phrase, locale })`

**Comment by mashpie** [comment]
nothing else to say
