### ISSUE TITLE
Uncaught ReferenceError: __ is not defined

### ISSUE THREAD

**Issue by Butonix** [mashpie/i18n-node#352]
hi
`import  i18n from 'i18n-2'
export class Navbar extends Component {
  constructor(props) {
    super(props)
  }
  render() {
    return (
        <li><IndexLink to="/" activeClassName={styles.active}>{__('Home')}</IndexLink></li>
  )
}`

`i18n.expressBind(app, {
  locales: ['ru', 'en'],
  directory: __dirname + '/locales',
  fallbacks: true,
  extension: '.js',
  defaultLocale: 'ru',
  cookieName: 'lang',
  register: global,
  api: {
    '__': 't',
    '__n': 'tn'
  }
});
app.use(function(req, res, next) {
  if(req.query.lang) {
    req.i18n.setLocaleFromQuery();
    res.cookie('lang', req.i18n.getLocale());
  } else {
    req.i18n.setLocaleFromCookie();
  }
  next();
});`

**Comment by PassTheMayo** [comment]
You're importing `i18n-2` and not `i18n` which means it's entirely a different module. Also, if you're using Express, use `i18n.configure({ ... })` where `...` is your configuration, and then do `express.use(i18n.init)`.

**Comment by mashpie** [comment]
Thanks for answering @PassTheMayo ! Let's close this issue.
