### ISSUE TITLE
objectNotation - issues with properties with dots in them

### ISSUE THREAD

**Issue by PassTheMayo** [mashpie/i18n-node#353]
I have a locale that looks like the following:

![image](https://user-images.githubusercontent.com/16949253/35885726-6d0f7d62-0b54-11e8-8eb4-3de6c0632025.png)

The problem with it is that I am trying to get the value of `commands -> bots -> footer -> discordbots.org` but it thinks I'm trying to get `commands -> bots -> footer -> discordbots -> org`. Is there any way I can make it get the correct value? I've tried to escape the `.` but no luck. I've also tried using `["discordbots.org"]` and still nothing. Any help?

**Comment by mashpie** [comment]
cleaning up some issues.. I guess meanwhile you found a solution but for reference: https://github.com/mashpie/i18n-node#object-notation

> To enable this feature, be sure to set objectNotation to true in your configure() call. Note: If you can't or don't want to use . as a delimiter, set objectNotation to any other delimiter you like.

So, `objectNotation: '~'` should work for example
