### ISSUE TITLE
Security issue: Error thrown if language param is twice in the URL

### ISSUE THREAD

**Issue by aguyinmontreal** [mashpie/i18n-node#356]
Beware all! can simply crash the app by using the language query twice in the URL.

`?lang=en&lang=en` will crash your app

Beware!

**Comment by Elias-Serneels** [comment]
Just ran into the same issue. It seems to come from this line right here:
`request.language = urlObj.query[queryParameter].toLowerCase();`
In this case `urlObj.query[queryParameter]` is an Array and calling toLowerCase on it will throw the Error.

**Comment by mashpie** [comment]
fix in PR #442 + regression test (pending)

**Comment by mashpie** [comment]
fixed by PR & released to npm as 0.11.0  - also check some extra edge cases covered in tests https://github.com/mashpie/i18n-node/blob/master/test/i18n.configureQueryParameter.js
