### ISSUE TITLE
Quotes and other special characters get HTML encoded

### ISSUE THREAD

**Issue by Bartinger** [mashpie/i18n-node#365]
Variables with special characters such as single and double quotes get HTML encoded.

For example:

```json
{
    "test1": "Hello ' <> \" characters",
    "test2": "Hello {{replace}}"
}
```

```typescript
18n.__('test1');
18n.__('test2', {replace: '<> \' "'});
```
will result in the following strings

```
test1 = "Hello ' <> " characters"
test2 = "Hello &lt;&gt; &#39; &quot;"
```
Is this a bug because I can't find a configuration to disable HTML encoding

**Comment by mashpie** [comment]
i18n doesn’t encode any strings. But template engines do. Please check with #138 etc.

**Comment by Bartinger** [comment]
@mashpie I found those issues as well, though I'm not rendering any HTML, the strings above come straight from i18n. Just found out i18n is using Mustache, so adding 3 brackets `{{{ ... }}}` fixes the issue.

So the following PR is no longer needed https://github.com/mashpie/i18n-node/pull/366

**Comment by chuck-park** [comment]
Thanks @dominicbartl
I found it on the document

![image](https://user-images.githubusercontent.com/15935262/144018553-7dafa094-fb20-4bf4-82d8-4da7f681bbc4.png)

**Comment by phosphore** [comment]
This should be in the docs or in the constructor of the package.

**Comment by mashpie** [comment]
feel free to submit an improving PR. 

It should posibly also adress the following:

People using mustache should Know how to use it https://github.com/janl/mustache.js#variables

People wanting to opt-out can do so by i18n.configure({mustacheConfig.disable: true}) as described quite high in https://github.com/mashpie/i18n-node#list-of-all-configuration-options
