### ISSUE TITLE
How Can i Make __mf act as hash list

### ISSUE THREAD

**Issue by Crackz** [mashpie/i18n-node#367]
i want to be able to make interpolation and get the same behaviour of hash list '__h'

**Comment by mashpie** [comment]
by adding a PR with a `__mfh` method

```js
  i18n.__mfh = function i18nTranslationHash(phrase) {
    var translations = [];
    Object.keys(locales).sort().forEach(function(l) {
      var hash = {};
      hash[l] = i18n.__mf({ phrase: phrase, locale: l });
      translations.push(hash);
    });
    return translations;
  };
```

and proper tests :) - that's the most time consuming part... and that's why I didn't add that "quickly".

**Comment by mashpie** [comment]
...and of course you could just use that function to decorate `i18n` within your app on your own

**Comment by Crackz** [comment]
i don't really remember what was my test case but thanks for helping
