### ISSUE TITLE
Using the | character

### ISSUE THREAD

**Issue by alsuga** [mashpie/i18n-node#370]
Hi, I'm trying to user the | character in a translation but doesn't work, \\| neither

**Comment by killmenot** [comment]
Duplicates: #309,  #386
Reference to docs: https://github.com/mashpie/i18n-node#ranged-interval-support

@alsuga 
Got the same problem. Here is the simplified workaround that I use in my project based on this answer https://github.com/mashpie/i18n-node/issues/309#issuecomment-300452543

```
{
 "foo": "bar &#124; baz"
}
```

```js
const htmlEntities = require('html-entities');
const entities = new htmlEntities.XmlEntities();
const decodeHtml = (s) => entities.decode(s);

const value = decodeHtml(__('foo')) //  'bar | baz'
```

**Comment by mashpie** [comment]
plus: #435 should mitigate that further
