### ISSUE TITLE
JSON from .js files?

### ISSUE THREAD

**Issue by blacksmoke26** [mashpie/i18n-node#375]
```js
"extension": ".js"
```

Any example to use `.js` files instead of `.json` files? 

Following code do nothing:
```js
module.exports = {
	'Hello': 'سلام'
};
```

**Comment by boxsnake** [comment]
As far as I see, this only read i18n config from `en.js` file other than `en.json`, and there is nothing different in the content.

**Comment by blacksmoke26** [comment]
Ah i see! Thank you.

**Comment by mashpie** [comment]
The `staticCatalog` option might also be useful for your use case https://github.com/mashpie/i18n-node#some-words-on-staticcatalog-option
