### ISSUE TITLE
Adding information about using triple moustaches to README

### ISSUE THREAD

**Issue by Christine-horrocks** [mashpie/i18n-node#376]
Hello,

I was encountering a problem with my url links if I passed them into a string in my translation file using double moustaches. Example:
en.json
"footer": {
"cookie-policy":` <a href='{{link}}'>Cookie Policy</a>`
}
Would end up looking like `<a href='&#x2F;meta&#x2F;cookie-policy'>Cookie Policy</a>` in the source code.

After a while of investigating I discovered that I needed to use triple moustaches.
Example:
en.json
"footer": {
"cookie-policy": `"<a href='{{{link}}}'>Cookie Policy</a>"`
}
Would end up looking like `<a href='/meta/cookie-policy'>Cookie `Policy</a>` in the source code.

Would it be possible to add this information into your README. Just so users in the future can find it more easily?

Thank you,
Christine

**Comment by romain10009** [comment]
Would be good! It bit me hard for 2 hours!

**Comment by mashpie** [comment]
mustache is mustache is mustache... 

Quote from https://mustache.github.io/mustache.5.html

> All variables are HTML escaped by default. If you want to return unescaped HTML, use the triple mustache: {{{name}}}.

---

*for future reference*

discussed in #138, #365, #35, #82, #102

and https://stackoverflow.com/questions/26269745/node-js-is-there-no-way-to-put-html-into-i18n-node-json-translation-files
