### ISSUE TITLE
When creating and editing files, localization at the end of the document does not set the line break

### ISSUE THREAD

**Issue by tomasevich** [mashpie/i18n-node#379]
### Description of the problem

Every time I have to make commits in **GitHub**, I pay attention to the fact that there is no control character in the localization files (`ru.json`,` en.json` ... etc) **ASCII** (**0x0A**, 10 in the decimal notation, **'\n'**).

![2018-08-15 10 40 09](https://user-images.githubusercontent.com/23076999/44131891-ade0e066-a077-11e8-8dbd-7a1b89bde007.png)

Perhaps this little thing will seem like a trifle to someone, but for me it's a bug!

### Possible Solution

Replace line **1126** in the file `i18n/i18n.js`

Before:
```js
fs.writeFileSync(tmp, JSON.stringify(locales[locale], null, indent), 'utf8');
```

> 1: {
> 2:    "index": "index"
> 3: }

After:
```js
fs.writeFileSync(tmp, JSON.stringify(locales[locale], null, indent) + '\n', 'utf8');
```

> 1: {
> 2:    "index": "index"
> 3: }
> 4:

### Expected Result

Each time localization files are updated, the line feed is appended to the document's end.

---

Thank you!

**Comment by mashpie** [comment]
well... that's how plain JSON.stringify writes (and reads) - for now let's stick to that. I'll keep that related to storage backend refactoring.
