### ISSUE TITLE
Add reload locale support

### ISSUE THREAD

**Issue by fkrauthan** [mashpie/i18n-node#38]
It would be good if there is a option to reload the locale manual. For example if env is development I like to watch the locale directory for changes and if there is a change I like to reload the changed file.

**Comment by mashpie** [comment]
#105 is about to get released - just needs more tests and support for prefix config

**Comment by SandeepBaranwal88** [comment]
Hi
autoReload is the good feature. It is working as expected when you running the application in dev environment.

It is not working when you will deploy this on docker :(
