### ISSUE TITLE
Select options not being translated

### ISSUE THREAD

**Issue by Karanval** [mashpie/i18n-node#383]
Hello, 
I have this piece of handlebars code:

`<select name="process">
    <option value="" disabled selected>{{i18n "select"}}</option>
    {{#each processes}}
      <option>{{i18n this}}</option>
    {{/each}}
 </select>`

Now the "select" is translated fine no matter how many changes I make to the locales, however {{i18n this}} is not, they are only being translated to the default language whichever language that is ( I tried changing it to different ones ) but always keeps only that translation, even when changing to other languages. 

Am I missing something? I have a suspicion it is being translated only once and for some reason it does not retranslate after?

Thanks for the feedback.

Best regards, 
Karolina

**Comment by mashpie** [comment]
you probably need to escape that scope by adding `@root` - like (untested):

```hbs
    <select>
        <option>{{__ 'pleaseSelect'}}</option> 
        {{#processes}} 
            <option>{{@root.__ this}}</option>
        {{/processes}}
    </select>
```
