### ISSUE TITLE
Replace sprintf with normal replace support

### ISSUE THREAD

**Issue by fkrauthan** [mashpie/i18n-node#39]
At the moment i18n supports something like that: `__('Hello %s, how are you today?', 'Marcus');` But if you now have to strings for example firstname and lastname and in one language you say `Hello firstname lastname` and in another `Hello lastname firstname` then you see that this system dosen't work. It would be better to have something like this `__('Hello %firstname% %lastname%', {'%firstname%': 'Max', '%lastname%: 'Mustermann'});` because now I can change the order of using parameters within a local. What do you think about that?

**Comment by mashpie** [comment]
released in 0.5.0 https://github.com/mashpie/i18n-node#mustache-support
