### ISSUE TITLE
plural __n does not match 0

### ISSUE THREAD

**Issue by gliluaume** [mashpie/i18n-node#394]
Trying to run given example from documentation provided in GitHub, with two languages I set:
## files
```bash
├── index.js
├── locales
│   ├── en.json
│   └── fr.json -> en.json

```
## index.js
```javascript
const i18n = require('i18n')

i18n.configure({
    locales:['en', 'fr'],
    directory: __dirname + '/locales'
});



function run() {
    console.log(i18n.getLocale())
    console.log(i18n.__n('dogs', 0)) // --> no dog
    console.log(i18n.__n('dogs', 1)) // --> one dog
    console.log(i18n.__n('dogs', 2)) // --> some dogs
    console.log(i18n.__n('dogs', 10)) // --> many dogs
    console.log(i18n.__n('dogs', 25)) // --> dozens of dogs
    console.log(i18n.__n('dogs', 42)) // --> a horde of 42 dogs
    console.log(i18n.__n('dogs', 199)) // --> too many dogs
}

i18n.setLocale('en');
run();

console.log('\n')
i18n.setLocale('fr');
run();
```

## en.json (please note that fr.json is a symbolic link to this one)
```json
{
	"dogs": {
		"one": "one dog",
		"other": "[0] no dog|[2,5] some dogs|[6,11] many dogs|[12,36] dozens of dogs|a horde of %s dogs|[100,] too many dogs"
	}
}
```

When I run `node index.js` I see:
```bash
en
no dog
one dog
some dogs
many dogs
dozens of dogs
a horde of 42 dogs
too many dogs


fr
one dog
one dog
some dogs
many dogs
dozens of dogs
a horde of 42 dogs
too many dogs
```
I expected in fr `No dog` as a first line. Exact same output as in en locale.

Version of i18n-node is 0.8.3.

**Comment by mashpie** [comment]
....well, plurals - a difficult story. `__n()` is using `make-plural` package (https://www.npmjs.com/package/make-plural) which provides precompiled versions of plural rules per language (http://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html) 

- in fr `one` may refer to 0 and 1
- while in en `one`refers to 1 only and 0 would be represented by `other`

to mitigate that you could add ranges to one two. In General `__n()` is to be used with a numerical placeholder so you should get 

```
0 dog
1 dog
```

so I guess you messages should better get translated by `__mf()` (https://github.com/mashpie/i18n-node#i18n__mf) or you should provide proper ranges for each language, but that would mean to study plural rules on your own.

**Comment by gliluaume** [comment]
ok, thank you for your answer
