### ISSUE TITLE
Untranspiled ES6 code in the library breaks in IE11

### ISSUE THREAD

**Issue by alexdonets** [mashpie/i18n-node#397]
I'm using next.js and i18n-node in my project and I get this syntax error
<img width="223" alt="Screenshot 2019-04-09 at 4 36 52 PM" src="https://user-images.githubusercontent.com/5912289/55809192-c758b180-5ae5-11e9-838c-4c79aa2541b4.png">

at this line in i18n/node_modules/debug/src/browser.js:157: 
`args[0].replace(/%[a-zA-Z%]/g, match => {`

I've tried different webpack configs to make it work, adding `require.resolve('i18n')` to js transpiler rule's _include_ list and many more.

Any idea on how to fix it?

**Comment by mashpie** [comment]
This is a server side module.
