### ISSUE TITLE
de.json vs. de-DE.json

### ISSUE THREAD

**Issue by mplwork** [mashpie/i18n-node#400]
When i have a de.json file in the locales directory and set the locale with `i18n.setLocale` to 'de-DE' the locale falls back to 'en'. How is this supposed to work?

**Comment by PrajvalRaval** [comment]
maybe try setting json file name as de-DE.json 🤔

**Comment by mplwork** [comment]
> 
> 
> maybe try setting json file name as de-DE.json 🤔

Yes, this will indeed work but then our Austrian and Swiss colleagues will complain. So, no, this is not a solution.

Java does it right where there is a default properties file which can be overridden with phrases from more specific language/country files. default.json, en.json, en-US.json etc.

**Comment by mashpie** [comment]
currently fallbacks need to be configured explicitly, I guess your case would be covered like this:

```js
const { I18n } = require("i18n");

const i18n = new I18n({
    locales:['it-CH', 'de-CH', 'de'],
    directory: __dirname + '/locales',
    fallbacks:{'de-*': 'de'},
});
```

so you end up with 3 files `it-CH.json, de-CH.json, de.json` 

- de-AT will get 'de'
- de-CH will get 'de-CH'
- de will get 'de'

see some more examples in https://github.com/mashpie/i18n-node/blob/master/test/i18n.fallbacks.js

**Comment by mplwork** [comment]
Thank you. This seems to be the solution indeed.
