### ISSUE TITLE
destructuring assignment is not working sometimes.

### ISSUE THREAD

**Issue by DylanJu** [mashpie/i18n-node#405]
I prefer to use destructuring assignment in es6.
and also i18n (my team use "react-i18next": "7.10.1")

but destructuring assignment with i18n is not working in some case

working case
```
_handleChangeLanguage = (e) => {
        const { i18n } = this.props;
        const language = e.target.value;
        i18n.changeLanguage(language);
    }
```

but if I change this, it's not working
```
_handleChangeLanguage = (e) => {
        const { changeLanguage } = this.props.i18n;
        const language = e.target.value;
        changeLanguage(language);
    }
```

with this error message:
```
Uncaught TypeError: Cannot set property 'language' of undefined
    at setLng (i18next.js:254)
    at changeLanguage (i18next.js:272)
```

I resolved it with working case but want to know why it occurred.

**Comment by mashpie** [comment]
I hope you found help at `i18next` (https://github.com/i18next/) - this is `18n-node` :)
