### ISSUE TITLE
Can I use typescript file(.ts) for extension instead of .json files 

### ISSUE THREAD

**Issue by omkarsunku** [mashpie/i18n-node#406]
Hello,

Can I use typescript file(.ts) for extension instead of .json files ?
If No: Supported extension files.
If Yes:Any related github repo/ sample demo which can help me.

Thanks

**Comment by mashpie** [comment]
yes and no - `i18n` is natively reading all files as json, no matter which extension is provided. BUT you could write your own loader for ts files and add your catalog by using `staticCatalog` option, see https://github.com/mashpie/i18n-node#some-words-on-staticcatalog-option
