### ISSUE TITLE
translation of validation msg inside router?

### ISSUE THREAD

**Issue by sreckovic** [mashpie/i18n-node#412]
I have problem to display translation inside router file for example I use
`const { check } = require('express-validator');`

if I include i18n inside router file
`const i18n = require('i18n');`

```
router.post(
  '/company/edit',
  [
    check('name')
      .exists({ checkFalsy: true })
      .withMessage(i18n.__('Full name is required.')),
  ],
  catchErrors(settings.postCompanySettings)
);
```

I am able to pull default translation but other then that it is not working, problem is that he doesn't get config from app.js file where I initialize i18n, what is proper way to handle something like this? Thanks!

**Comment by mashpie** [comment]
same as in #410 you need to use `req.__()` instead of `i18n.__()`

**Comment by sreckovic** [comment]
@mashpie thanks on your reply, much appreciated!

for some reason I get
`ReferenceError: req is not defined`

when I use for example
```
router.post(
  '/login',
  [
    check('email')
      .exists({ checkFalsy: true })
      .withMessage(req.__('Please enter e-mail address.')),

    body('email')
      .isEmail()
      .withMessage(req.__('E-mail address is not valid.'))
      .normalizeEmail({ gmail_remove_dots: false }),

    body('password', req.__('6 characters is minimum for password.'))
      .isLength({ min: 6 })
      .isAlphanumeric()
      .trim(),
  ],
  catchErrors(auth.postLogin)
);
```

I load routers inside app.js like this
```
const authRoutes = require('./routes/auth');
app.use('/auth', authRoutes);
```

**Comment by mashpie** [comment]
express docs should help http://expressjs.com/en/guide/writing-middleware.html#writing-middleware-for-use-in-express-apps

**Comment by sreckovic** [comment]
Problem here is with express-validator, req is not avaiable by default, I needed to use custom dynamic messages.

```
router.post(
  '/login',
  [
    body('email')
      .exists({ checkFalsy: true })
      .withMessage((value, { req, location, path }) => {
        return req.__('Please enter e-mail address.', { value, location, path });
      }),
  ],
  catchErrors(auth.postLogin)
);
```
@mashpie thanks for your help, you pointed me in right direction!
