### ISSUE TITLE
I18n using Vue and pug

### ISSUE THREAD

**Issue by DougLocklin** [mashpie/i18n-node#415]
I am dynamically rendering a list of values in a vue.js application. That part is straightforward using the handlebars/mustache syntax.

```
const types = {
    type_a: {
        key1: "value1",
        key2: "value2",
        label: "My label1",
        I18n_label: #{i18n.__("My label1")}
    },
    type_b: {
        key1: "value1",
        key2: "value2",
        label: "My label2",
        I18n_label: #{i18n.__("My label2")}
    }
  }

li.list-group-item.row(v-for='type in types')
              .col.col-xs-10
                span.span {{type.label}}
```

However, I also need for those values to be translated. 

This doesn’t work:
```
li.list-group-item.row(v-for='type in types')
              .col.col-xs-10
                span.span {{type.I18n_label}}
```

Nor does this:

```
const types = {
    type_a: {
        key1: "value1",
        key2: "value2",
        label: "My label1",
        I18n_label: `${i18n.__("My label1")}`
    }…
```

I also tried creating a function to compute the values (converting "My label1" to ${i18n.__("My label1")} but that didn't work for me either. 

Any suggestions?

**Comment by mashpie** [comment]
i18n is for nodejs based server side use. There are some dedicated high level modules out there to cope with client side and vue in particular. I advise you to look into [vue-i18n](https://www.npmjs.com/package/vue-i18n) for example.
