### ISSUE TITLE
TypeError: logWarnFn is not a function

### ISSUE THREAD

**Issue by thaind97git** [mashpie/i18n-node#417]
When I try to translate text in my service in current project like this:
```javascript
if (!lib) {
    throw new Error(
      `${i18n.__('services.crypto_libs.get_by_coin_id.not_support')} 
      ${coinId} 
      ${i18n.__('services.crypto_libs.get_by_coin_id.not_avaliable')}`
    );
  }
```
I get an error like this:
![image](https://user-images.githubusercontent.com/42630357/68267868-7a8e8680-0086-11ea-9679-faf04e6a9518.png)

I find in `node_modules code` , I see that:
```javascript
// required warn
warn = require('debug')('i18n:warn')

// define logWarnFn
logWarnFn = (typeof opt.logWarnFn === 'function') ? opt.logWarnFn : warn; // line 147

// call function logWarnFn
function logWarn(msg) {
    logWarnFn(msg); // line 1169
}
```

I guess `warn` at 147 is not a function, because I see they checked `typeof opt.logWarnFn === 'function'`. But I can not resolve this error.
Any suggestions?

**Comment by nyeu** [comment]
I'm having the same issue, any idea on how to fix it?

**Comment by mashpie** [comment]
by default i18n uses [debug](https://www.npmjs.com/package/debug) which perfectly returns `warn` as function.

Still there are config options to "inject" a custom logging function `opt.logWarnFn`. 

Looking at your trace and comparing line numbers of it with current code... wired, they can't match at all:

- https://github.com/mashpie/i18n-node/blob/master/i18n.js#L1169
- https://github.com/mashpie/i18n-node/blob/master/i18n.js#L147

**Comment by thaind97git** [comment]
Because at the main file server I loaded `my service middleware` **before** load `i18n middleware`, So I got this error at some time.
I resolved this issue by move `i18n middleware` to before `my service middleware`.
Code error:
```
app.use(apis);
app.use(i18n);
```
Code correct:
```
app.use(i18n);
app.use(apis);
```

**Comment by thaind97git** [comment]
> I'm having the same issue, any idea on how to fix it?

Hi @nyeu , I hope my comment can help you.

**Comment by axelpale** [comment]
I had the same problem. In my case the problem was in the execution order. My route handlers called `i18n.getLocale()` before `i18n.configure(...)`.

The cause was a bit hard to detect. It would be more helpful if the error message talked about failed configuration instead of a missing logWarnFn.
