### ISSUE TITLE
Error translating dynamic content

### ISSUE THREAD

**Issue by robsilva** [mashpie/i18n-node#418]
My translations work perfectly with static text like this:
{{{ __ "some string" }}}

But I was wondering how I might go about translating dynamic content from my database, like so:
```
{{#each issues}}
   <a href="/issues/{{slug}}" class="text-white font-weight-bold text-uppercase">{{{ __ title }}}</a>
{{/each}}
```
where 'title' is dynamic prop of my mongoose model.

I am getting: Error: Missing helper: "__" 

Also tried:
{{{ ../__ title }}} // no errors, but doesn't translate

**Comment by robsilva** [comment]
Nevermind, I can do the translation in my controller...

**Comment by mashpie** [comment]
just to comment on handlebar blocks: They use nested contexts while helpers are attached to root context only. In short, this should work:

```hbs
{{#each issues}}
   <a href="/issues/{{slug}}" class="text-white font-weight-bold text-uppercase">{{{ @root.__ title }}}</a>
{{/each}}
```

change `{{{ __ title }}}` to `{{{ @root.__ title }}}`

see https://stackoverflow.com/questions/17364897/access-to-root-context-in-handlebar-js-template and https://handlebarsjs.com/reference.html (search for @root)
