### ISSUE TITLE
I have module i18n error

### ISSUE THREAD

**Issue by yordanjose** [mashpie/i18n-node#421]
1206 error Linux 4.15.0-20-generic
1207 error argv "/usr/bin/node" "/usr/bin/npm" "install" "i18n" "--save"
1208 error node v8.10.0
1209 error npm  v3.5.2
1210 error code EMISSINGARG
1211 error typeerror Error: Missing required argument #1
1211 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
1211 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
1211 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
1211 error typeerror     at /usr/share/npm/lib/install/deps.js:457:7
1211 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1211 error typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
1211 error typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
1211 error typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
1211 error typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
1211 error typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
1212 error typeerror This is an error with npm itself. Please report this error at:
1212 error typeerror     <http://github.com/npm/npm/issues>
1213 verbose exit [ 1, true ]

**Comment by mashpie** [comment]
I'm afraid this is a npm related error message:

```
1212 error typeerror This is an error with npm itself. Please report this error at:
1212 error typeerror http://github.com/npm/npm/issues
```

not originating from i18n.

**Comment by yordanjose** [comment]
Thank you very much for your reply
