### ISSUE TITLE
How get localized string from optional unknown locale?

### ISSUE THREAD

**Issue by rraallvv** [mashpie/i18n-node#427]
In my Telegram bot the locale is optional and it can change for different users. So, I was thinking maybe I could do something like this:

```javascript
let mylocale; // Optional and could be not supported by the bot

const locales = i18n.getLocales();
const locale = locales.indexOf(mylocale) !== -1 ? mylocale : i18n.getLocale();

const localizedString = i18n.__h('Helo')[locale];
```

Is there a straight forward way to get a localized string with an optional locale?

**Comment by mashpie** [comment]
if I get you right, that setup should be fine:

```js
const { I18n } = require('i18n')

const i18n = new I18n({
    locales:['en', 'de'],
    directory: __dirname + '/locales',
    defaultLocale: 'en',
    retryInDefaultLocale: true
})
```
later... in CLI style script

```js

console.log(i18n.__('Hello')) // will be "Hallo" for 'de' and Hello for 'en' and any other
```

or... in any connect style webapp like express

```js
const app = express()
app.use(cookieParser())
app.use(i18n.init)

app.get('/home', (req, res) => {
  res.send(res.__('Hello'))
})

```

**Comment by rraallvv** [comment]
I'm no sure whether I missed the `defaultLocale` option before or it was something added recently but that's what I was looking for. Thank you so much.

**Comment by mashpie** [comment]
Hey @rraallvv, glad to have helped you. In fact `defaultLocale` pretty much turns 9y these days, while `retryInDefaultLocale` is the _freshly published_ (v.0.13.0) little sister - playing nicely together :)
