### ISSUE TITLE
Error introducing "<" & ">"

### ISSUE THREAD

**Issue by Hugovidafe** [mashpie/i18n-node#430]
The result when I want to introduce "<" or ">" is "`&lt;`" or "`&gt;`"

EDIT: 
> "`&lt;`" or "`&gt;`"
> instead of 
> "&lt;" or "&gt;"

**Comment by mashpie** [comment]
true!

related to #376 ?

**Comment by Hugovidafe** [comment]
Sorry, it did not appear as it should.

I think isn't related to #376...

**Comment by mashpie** [comment]
Alright, so we van close?

**Comment by Hugovidafe** [comment]
But I'm seeing `&lt;` and `&gt;` instead of "<" and ">", what could be the solution?

**Comment by mashpie** [comment]
How that? Please add an example.

All issues with encoded enties originate from the chosen template engine. Template engines default to encode any given string to prevent code injection. Each engine provides it's own methods to come around that, ie. (`encoded` vs `plain`):

- `{{}}` vs. `{{{}}}` in mustache, handlebars
- `<%- %>` vs. `<%= %>` in ejs
- `{}` vs. `!{}` in pug
- etc.

follow links from last comment in https://github.com/mashpie/i18n-node/issues/376#issuecomment-623156341

**Comment by Hugovidafe** [comment]
I remember it was with {{ and }}

**Comment by mashpie** [comment]
Sounds like mustache or hbs. So try with {{{}}}.

**Comment by Hugovidafe** [comment]
I tried, and works perfectly!
Thanks!
