### ISSUE TITLE
Problems extending i18n

### ISSUE THREAD

**Issue by ghost** [mashpie/i18n-node#434]
I want to create this:
```js
const i18n = require('i18n')

class Langs extends i18n {
    constructor(api) {
        this.api = api;
        if (this.api.options.path_langs) {
            this.configure({
                directory: this.api.options.path_langs,
                syncFiles: true,
                updateFiles: true,
                autoReload: true
            })
            super();
        } else {
            throw new Error("You need to specify a path to use as localization folder.");
        }
    }
    
}

module.exports = Langs;
```

But I'm having an error:
![image](https://user-images.githubusercontent.com/37117197/85961069-2420e000-b9a8-11ea-806d-b2079917ee7e.png)

Any suggestion or help would be great!

**Comment by mashpie** [comment]
i18n is just a plain js module exporting an object. Not a class and so can't get extended and has no constructor. But folks at phrase have written a nice tut about abstracting i18n in an class based interface https://phrase.com/blog/posts/node-js-i18n-guide/ - I guess that should help to get on track...
