### ISSUE TITLE
how to use req.getLocale with typeScript?

### ISSUE THREAD

**Issue by TheOneAndOnlyGarcia** [mashpie/i18n-node#444]
Hello, 

the docs are stating that i can get the locale by calling `req.getLocale(); // --> de`. As soon as i am trying to compile my js into ts the compiler breaks:

```
error TS2339: Property 'getLocale' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs>'.
127  	const locale = req.getLocale()
```

is there any type definition i can use? thanks!

**Comment by mashpie** [comment]
TS... :( how about `res.getLocale()` - assuming it should work as what I get from https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/i18n/index.d.ts#L290 and https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/i18n/i18n-tests.ts#L218 

Question should be: "how to use i18n with typescript". The module itself still is written in plain old js - even without many es6. Types currently get provided by https://github.com/DefinitelyTyped/DefinitelyTyped with a package: https://www.npmjs.com/package/@types/i18n which will always be a bit behind the current version of `i18n`.

Lastly those type defs even messed up with express's `res.locals` - PR ist open. Sometimes I will provide definitions by myself.

**Comment by mashpie** [comment]
Should be resolved as soon PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47811) got merged

**Comment by mashpie** [comment]
PR got merged an published a while ago
