### ISSUE TITLE
npx npm-force-resolutions failed

### ISSUE THREAD

**Issue by amlrJan2015** [mashpie/i18n-node#445]
15:46:43 npm ERR! code ELIFECYCLE
15:46:43 npm ERR! errno 1
15:46:43 npm ERR! i18n@0.13.0 preinstall: `npx npm-force-resolutions`
15:46:43 npm ERR! Exit status 1
15:46:43 npm ERR! 
15:46:43 npm ERR! Failed at the i18n@0.13.0 preinstall script.

**Comment by amlrJan2015** [comment]
> i18n@0.13.0 preinstall /Users/amlr/gv/web/desktop-html/node_modules/i18n
> npx npm-force-resolutions

npx: installed 5 in 1.571s
ENOENT: no such file or directory, open './package-lock.json'

**Comment by mashpie** [comment]
Thanks for spotting... about to retest

**Comment by mashpie** [comment]
I knew... there will be some issue with _13th_ release... removed pre-install (doesn't make sense in that case anyway) 

- [x] npm branch passed CI

- [x] install by `npm install https://github.com/mashpie/i18n-node.git#npm --save` succeeds

about to publish hotfix

**Comment by mashpie** [comment]
hotfix published as i18n@0.13.1 (https://github.com/mashpie/i18n-node/releases/tag/0.13.1) 

@amlrJan2015, would you mind to retry?

**Comment by amlrJan2015** [comment]
It is now running without errors. Thanks for the quick fix.
