### ISSUE TITLE
staticCatalog does not exist for configuration (TypeScript)

### ISSUE THREAD

**Issue by CypElf** [mashpie/i18n-node#448]
I would like to use the `staticCatalog` property of the configuration function to load the translations from YAML files. My project is using TypeScript and so I use the [typed](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/i18n/index.d.ts) version of i18n, but in this one, the property `staticCatalog` does not exist : 
```
Object literal may only specify known properties, and 'staticCatalog' does not exist in type 'ConfigurationOptions'.
```
What can be done instead ?

**Comment by mashpie** [comment]
there is PR pending which should fix that issue https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47811

**Comment by CypElf** [comment]
Thanks. I guess I'll have to wait until it's merged

**Comment by CypElf** [comment]
Pull request merged
