### ISSUE TITLE
Issues with PM2 watch

### ISSUE THREAD

**Issue by NotNotMarshall** [mashpie/i18n-node#449]
Using autoreload : true causes troubles with PM2 watchers I don't know how and why.
Whenever I visit a page of my server pm2 automatically triggers a restart saying that file xyz.json was changed in langs folder.

Somehow:
1. When I set autoreload to false everything works fine but sometimes (like 10% of times) I face this restart again (been testing for the last 48 hours).
2. When I ignore the langs folder from being watched by pm2 then everything works fine 100%.

So what seems to be the problem? is i18n brining any changes to the file randomly? Or are the system watchers conflict with each other?

**Comment by NotNotMarshall** [comment]
@mashpie  Hell-fucking-o!!??

**Comment by mashpie** [comment]
pardon..??

---

```
  // watch for changes in JSON files to reload locale on updates - defaults to false
  autoReload: true,

  // whether to write new locale information to disk - defaults to true
  updateFiles: false,

  // sync locale information across all files - defaults to false
  syncFiles: false,
```

---

I could eventually provide a working ecosystem.json for pm2 within that demo setup https://github.com/mashpie/i18n-express-hbs-prefix
