### ISSUE TITLE
Special characters not supported as argument to __

### ISSUE THREAD

**Issue by PierreTurnbull** [mashpie/i18n-node#450]
Hi,

It seems like some special characters are not supported as argument to `__`. They are replaced with a character code instead. For example, `/` is replaced with `&#x2F;` and `"` is replaced with `&quot;`.

Steps to reproduce : 

index.js
```js
const i18n = require('i18n')

i18n.configure({
    directory: path.join(__dirname, 'translations'),
})

console.log(i18n.__({ phrase: "test", locale: "en" }, { var: '/' }))
console.log(i18n.__({ phrase: "test", locale: "en" }, { var: '"' }))
```

translations/en.json
```
{
    "test": "{{var}}"
}
```

Version in package.json : `"i18n": "^0.13.2"`

**Comment by mashpie** [comment]
please try with `{{{var}}}` - read https://github.com/mashpie/i18n-node#how-about-markup

It's related to how mustache escapes any input. Tripple `{{{}}}` disables that.

**Comment by PierreTurnbull** [comment]
This effectively solves my problem, thank you.

**Comment by juicycool92** [comment]
issues are closed long time ago, but still save my day!

can you consider to add description on README.md? @mashpie 
I think there are people like us are struggled with same issues.

Thanks for share good modules!

**Comment by mashpie** [comment]
@juicycool92 you mean like https://github.com/mashpie/i18n-node#how-about-markup?

**Comment by juicycool92** [comment]
> @juicycool92 you mean like https://github.com/mashpie/i18n-node#how-about-markup?

yes!... Oof 
sorry for not read document properly
