### ISSUE TITLE
Load messages async

### ISSUE THREAD

**Issue by shahdivyesh** [mashpie/i18n-node#452]
I am trying to load messages using the endpoint. To do that I have implemented the following code. Screen shot below.
![image](https://user-images.githubusercontent.com/71421745/104536841-74772c80-55de-11eb-8943-9f87ac27c9fb.png)
![image](https://user-images.githubusercontent.com/71421745/104536887-8c4eb080-55de-11eb-85f9-0c495306582b.png)
![image](https://user-images.githubusercontent.com/71421745/104536978-b3a57d80-55de-11eb-8cf0-143e8c8ac59a.png)

I am getting the following error

![image](https://user-images.githubusercontent.com/71421745/104537216-27e02100-55df-11eb-82aa-3fbb3e6b7374.png)

Any idea what could be causing translation to not loaded in "messages". The endpoint is good. I have validated that and confirmed data are coming back. I believe It's an issue with the promise.

**Comment by mashpie** [comment]
The error reported to console directly relates to vue-i18n not i18n-node :)

Maybe you should try ower there: https://github.com/kazupon/vue-i18n

**Comment by shahdivyesh** [comment]
Thank you!!!

**Comment by mashpie** [comment]
you're welcome :) So 'Ill close this.
