### ISSUE TITLE
setLocale doesnt work

### ISSUE THREAD

**Issue by swana1337** [mashpie/i18n-node#455]
so i configured the app like we see here:  
![image](https://user-images.githubusercontent.com/33859359/108062933-c89c8300-705a-11eb-923b-3ef564f1a190.png)
i set the default language to DE

as you can see i made an function called changeLanguage, this one you see here:
![image](https://user-images.githubusercontent.com/33859359/108063188-2335df00-705b-11eb-94b0-0729b70b852d.png)

the two logger information show both the language is EN

BUT always the de.json is used. So it ALWAYS falls back to the default even if it is set!

Please can anyone help?

**Comment by mashpie** [comment]
`i18n.setLocale()` and `i18n.getLocale()` as used above, won't effect `req` or `res` objects. You need to bind to that context as written here: https://github.com/mashpie/i18n-node#i18nsetlocale like so:

```js
req.setLocale('de')
req.getLocale() // --> de
```

**Comment by swana1337** [comment]
![image](https://user-images.githubusercontent.com/33859359/108159616-b0267a00-70e7-11eb-997d-1d2e5559c531.png)

when i try it this way, the loggers say it is changed to EN.

but it doesn't change the language on my site. The website is always in german again. 
I don't know what to do i also tried all the commented commands but nothing will work. I don't know why..

**Comment by mashpie** [comment]
Maybe your template engine is still using global scope instead of req context?

**Comment by swana1337** [comment]
the template engine is set as you can see on the first picture. I think this is right?

**Comment by swana1337** [comment]
i also tried to put it behind the changeLanguage function but this still don't work

**Comment by mashpie** [comment]
Your screenshot shows a global assignment. That won't work. Can you provide a demo repository with your complete implementation?

**Comment by swana1337** [comment]
this is already the whole code for the i18n ..

in njk I use it like this then:
{{ __("generalInformation") }}

**Comment by swana1337** [comment]
if i set the defaultLocale new in the changeLanguage function it works. but this is not the solution i need cause the defaultLanguage shouldn't change.

**Comment by mashpie** [comment]
`defaultLoacle` is just a fallback to locale guessing of incoming requests. As far as I get it, you have bound the __global__ `i18n.__` as a helper with `env.addGlobal('__', i18n.__)`, which won't use the req context at all. By default, nunjucks exposes `res.locals` in templates, so you might try with 

```hbs
{{ res.locals.__("generalInformation") }}
```

instead of

```hbs
{{ __("generalInformation") }}
```

or bind `req.__` within your middleware instead of `i18n.__` as your helper, ie.:

```js
app.use((req, res, next) => {
  env.addGlobal('__', req.__)
  next()
})
```

Unfortunately, I am not entirely familiar with nunjucks and can't talk from experience.

Again, debugging and fixing would be easier with a reproducible demo repository.

**Comment by swana1337** [comment]
OMG thanks so much now it works !!!

**Comment by mashpie** [comment]
Glad to have helped! Just for reference: Which one provided the final solution?

**Comment by swana1337** [comment]
or bind req.__ within your middleware instead of i18n.__ as your helper, ie.:

app.use((req, res, next) => {
  env.addGlobal('__', req.__)
  next()
})

Thanks so much!!
