### ISSUE TITLE
Object notation inside locales files is supported?

### ISSUE THREAD

**Issue by flacanellas** [mashpie/i18n-node#456]
I'm looking for object notation inside locale json files... it could be pretty helpfull. Is supported?

I mean something like this...
```json
{
    "author": {
        "name": "Francisca Cañellas"
    },
   "app": {
      "meta": {
          "author": "author.name"
      }
   }
}
```
I'm wonder if there is not supported yet I could code it, but I wanted ask first...
Thanks in advance!

**Comment by damnx** [comment]
In addition to the traditional, linear translation lists, i18n also supports hierarchical translation catalogs.

To enable this feature, be sure to set objectNotation to true in your configure() call. Note: If you can't or don't want to use . as a delimiter, set objectNotation to any other delimiter you like.

Instead of calling __("Hello") you might call __("greeting.formal") to retrieve a formal greeting from a

**Comment by flacanellas** [comment]
Thank you for your answer but this is not what i'm looking for.
After a few hours reading source I made a enchancement function to cover my needs (_it's need ES6_).

Given this json translate:
```json
{
    "author": {
        "name": "Francisca Cañellas",
        "about": "{root.author.name} is a young girl developer who like coding in her free time!"
    },
   "app": {
      "meta": {
          "author": "root.author.name"
      }
   }
}
```
I used `root.` prefix to know which non space text is an object notation, and I used `{prefix.object-notation}` to catch a non text word inside long/paragraph text.

Then once initialized properly i18n I overrided global function `__` with this simple wrapper function:
```javascript
// ... some gulpfile js code
// ...

const i18n = new I18n({
    autoReload: true,
    locales: ['es'],
    directory: DIR.locales,
    objectNotation: true,
    register: global
});
i18n.setLocale('es');

// I18n JSON INHERITANCE EXTERNAL ENHANCEMENT
global['__'] = function __(phrase) {
    // USED FOR DETECT JSON INHERITANCE
    let jsonParentPrefix = 'root.';
    let jsonParentPrefixRe = /[^{]{1}root\./g;
    // EXTRACT INHERITANCE DEFINITION INSIDE STRINGS
    let jsonInStringRe = /(?:\{((?:[a-z_\-]*\.)(?:[a-z_\-]*\.?)+)*\})+/gm;
    // USED FOR CLEAN TRANSLATION ID
    let jsonInStringDelimitor = /\{|\}|root\./g;
    let translation = '';

    // DETECT JSON INHERITANCE FOR STRING ARGUMENTS
    if ( typeof phrase === 'string' ) {
        translation = i18n.__(phrase);

        // DETECT JSON INHERITANCE
        if ( jsonParentPrefixRe.test(translation) ) {
            translation = __( translation.replace(jsonParentPrefix, '') );
            console.log(phrase, translation);
        }

        // DETECT JSON INHERITANCE INSIDE STRING
        if ( jsonInStringRe.test(translation) ) {
            // COLLECT INHERITANCE FROM TRANSLATION STRING
            let translationList = translation.match(jsonInStringRe)
                .map(e => {
                    return {
                        key: e,
                        value: __( e.replace(jsonInStringDelimitor, '') )
                    }
                });

            // INSERT TRANSLATIONS IN STRING
            for ( let i = 0; i < translationList.length; i++ )
                translation = translation.replace( translationList[i].key, translationList[i].value );
        }


    // REDIRECT TO i18nTranslate function
    } else { translation = i18n.__(phrase); }

    return translation;
};

//...
// ... some gulpfile js code
```

Properly the results are the following:

`author.about`: _Francisca Cañellas is a young girl developer who like coding in her free time!_
`app.meta.author`: _Francisca Cañellas_

I think it's could be better but for me is good enought (_for now_).

P.s. with the wrapper function you don't have to modify any of the source and is portable.
Regards

**Comment by flacanellas** [comment]
Question Resolved!
