### ISSUE TITLE
How to set locale global ?

### ISSUE THREAD

**Issue by golubvladimir** [mashpie/i18n-node#460]
I use template - [https://github.com/januwA/nest-i18n-example](https://github.com/januwA/nest-i18n-example).

I set up i18n global.

```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as i18n from 'i18n';
import * as path from 'path';
import * as cookieParser from 'cookie-parser';

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  //app.use(cookieParser());

  i18n.configure({
    header: 'accept-language',
    locales: ['ru', 'en'],
    directory: path.join(__dirname, '/locales'),
  });

  app.use(i18n.init);

  await app.listen(3000);
}
bootstrap();
```
Use in module 
```
import { Injectable, Inject, Scope } from '@nestjs/common';
import { REQUEST } from '@nestjs/core';
import { Request } from 'express';
import * as i18n from 'i18n';

@Injectable({ scope: Scope.REQUEST })
export class AppService {
  constructor(@Inject(REQUEST) private req: Request) {}

  getHello() {
    return i18n.__('hello');
  }
}
```
I try to change accept-language header in postman, but lang don't change.

**Comment by mashpie** [comment]
This won't work in global mode! Global is suitable for server side cli use __only__. You somehow need to use the requests translation method, like

```js
req.__('hello')
```

or maybe

```js
this.req.__('hello')
```

Unfortunately, I can't help with nest. Never tried that framework - but hey, maybe a module intended to be used with nest will help out: https://www.npmjs.com/package/nestjs-i18n

Another nice article you might consider for inspiration https://phrase.com/blog/posts/node-js-i18n-guide/

**Comment by golubvladimir** [comment]
I fix in main.ts and it works
```
import { NestFactory } from '@nestjs/core';
import { AppModule } from './app.module';
import * as i18n from 'i18n';
import * as path from 'path';
import * as parser from 'accept-language-parser';

function getLocale(req) {
  console.log(parser.parse(req.headers['accept-language']));

  return parser.parse(req.headers['accept-language'])[0]['code'];
}

async function bootstrap() {
  const app = await NestFactory.create(AppModule);

  i18n.configure({
    locales: ['ru', 'en'],
    directory: path.join(__dirname, '/locales')
  });

  app.use((req, res, next) => {
    i18n.setLocale(getLocale(req));

    next();
  })

  app.use(i18n.init);

  await app.listen(3000);
}
bootstrap();

```

**Comment by mashpie** [comment]
Still this looks like to raise issues on concurrent requests, because I can't see i18n bound to any request context or scope. If I am right, you will encounter situations where multiple requests will overwrite each others "global" settings. AFAIK your middleware should be implemented like so:

```js
  app.use((req, res, next) => {
    i18n.setLocale(req, getLocale(req));

    next();
  })
```

and any later translation should use the scoped api like `req.__()`, `req.__n()` etc.
