### ISSUE TITLE
Lang parameter in root (website.com/en/home) work hasardly.

### ISSUE THREAD

**Issue by Macha-orange** [mashpie/i18n-node#463]
Hello,

I have a website with NodeJS + Express + EJS and I want my langage parameter in root url like this :
www.website.com/en/home
www.website.com/fr/home

So here my set up :
```

let lang = "en";
app.locals.lang = "en";

const i18n = require('i18n')

i18n.configure({
    locales: ['en', 'fr','cn'],
    directory: ('./locales'),
})

app.use(i18n.init)

app.use((req, res, next) => {
        next();
});

app.get('/:lang/home', (req, response) => {
    lang = req.params.lang;
    app.locals.lang = req.params.lang;
    response.render('pages/home', { lang:lang })
})



// home.ejs page
<%- include('header.ejs'); -%>
<a href="/<%=lang%>/index">Go to webpage index</a>


```

I need to setup "app.locals.lang = "en"; because when I don't do that, I have a lot of error in "header.ejs" because "lang" is not defined, even if I put <%- include('header.ejs', {lang:lang}); -%>.

The traduction works great for english but for other it's quite hasardly. It can sometimes work few times in a row then every other language /fr/ and /cn/ switch to english.

The only page that don't have this problem is a "random button webpage" like this 

```
app.get('/:lang/randompage', (req, response) => {
    lang = req.params.lang;
    app.locals.lang = req.params.lang;
    let randomFile = // home or root or other
    res.redirect('/'+lang+'/'+randomFile);
})
```

So the last app.get redirect to another app.get and language switch is instant but for every other sometimes it works and sometimes not ?

**Comment by mashpie** [comment]
Looks like you don't set the locale of i18n anywhere. Please check out example https://github.com/mashpie/i18n-express-hbs-prefix

**Comment by Macha-orange** [comment]
Thank you for the link it works very good now !
