### ISSUE TITLE
Maximum call stack size exceeded with some settings

### ISSUE THREAD

**Issue by thib3113** [mashpie/i18n-node#493]
I think I found a bug,
I'm using version 0.14.1 . 

I'm using the options : 
```
retryInDefaultLocale = true;
syncFiles: true,
```

So when I translate : 
 - `i18nTranslate` => call `translate`
 - `translate` see `(!skipSyncToAllFiles && syncFiles) === true` => call `syncToAllFiles`
 - `syncToAllFiles` => call `translate` with `skipSyncToAllFiles = true`
 - `translate` go to [here](https://github.com/mashpie/i18n-node/blob/master/i18n.js#L1050) (same [here](https://github.com/mashpie/i18n-node/blob/master/i18n.js#L1028)) => call translate file without `skipSyncToAllFiles`
 - `translate` see `(!skipSyncToAllFiles && syncFiles) === true` => call `syncToAllFiles` (and then, restart the loop) . 
 
 
Maybe passing syncToAllFiles [here](https://github.com/mashpie/i18n-node/blob/master/i18n.js#L1050) and [here](https://github.com/mashpie/i18n-node/blob/master/i18n.js#L1028), can be a quick fix

**Comment by mashpie** [comment]
would you be able to setup a minimal reproduction repository?

**Comment by thib3113** [comment]
@mashpie here is it : https://github.com/thib3113/i18n-493-issue . 

But, it's mostly : 
```
const { I18n } = require("i18n");
const path = require("path");

const i18n = new I18n({
    locales: ["en", "de"],
    directory: path.join(__dirname, "locales"),
    // you may alter a site wide default locale
    defaultLocale: "en",

    // will return translation from defaultLocale in case current locale doesn't provide it
    retryInDefaultLocale: true,
    // sync locale information across all files - defaults to false
    syncFiles: true,
});

i18n.__("test");

```
Setting `syncFiles` and `retryInDefaultLocale` in the same times that produce the bug .

**Comment by mashpie** [comment]
Thanks, will look into it over weekend probably

**Comment by mashpie** [comment]
Thank you @thib3113 for reporting and analysing. Your guess for a fix was also perfectly right. I've just added tests to cover your issue. 

A new version `0.14.2` should be released within minutes
