### ISSUE TITLE
passing a zero number value (0) incorrectly returns the full json string, brackets and all, without injecting the replacement value

### ISSUE THREAD

**Issue by mikeyamato** [mashpie/i18n-node#497]
Whenever I try passing a zero (`0`) number value what returns is the original JSON string with brackets and the key name. Any other number value that gets passed is injected correctly. 

```
// JSON
{
  "greatJobPracticedWords": "Great job! You practiced {{number}} of your saved words today.",
}
```
when passing a zero number value, `i18next.t('greatJobPracticedWords', { number: 0 });`, I get the following:
![Screen Shot 2022-05-20 at 10 25 28](https://user-images.githubusercontent.com/27756216/169581381-1f0ed04a-01ef-4a4e-bb03-fd408ab8bb64.png)

All other number values passed, `i18next.t('greatJobPracticedWords', { number: 1 });`, I get the following:
![Screen Shot 2022-05-20 at 10 26 18](https://user-images.githubusercontent.com/27756216/169581452-bb87418b-7bf3-4cfb-9ef2-42b2faeba536.png)

**Comment by mashpie** [comment]
better ask @adrai over at https://github.com/i18next/i18next ;)

**Comment by adrai** [comment]
@mikeyamato seems to work: https://codesandbox.io/s/react-i18next-http-example-forked-ui9p6j?file=/src/app.js:838-895
<img width="928" alt="image" src="https://user-images.githubusercontent.com/1086194/169594563-c21d5ca5-5044-4d8d-a432-dedb7e75814b.png">

**Comment by mikeyamato** [comment]
Thanks for confirming. I'm going to be extremely embarrassed if this turns out to be a local setting (inherited project).
