### ISSUE TITLE
When i18n is packaged into exe cannot be used, i18n directory cannot find the files under the directory path.

### ISSUE THREAD

**Issue by Yomisana** [mashpie/i18n-node#499]
Hello everyone,
When I am debugging, the software can read my language files normally, but after I package it, it seems that it cannot be read because locales folder are in asar? But the error messages all point to the i18n package, so I want to ask this How to deal with it?
error picture: https://dev.yomisana.xyz/20220714_code_error_screenshot
:shipit:  | default asar file | asar file(use asarmor) | unpack asar(folder name: app.asar)
:------------ | :-------------| :-------------| :-------------
status | :x: |  :x: | :heavy_check_mark:

❌ can't work
✔️ can work

project tree (electron)
````
Mjolnir LeagueLite
├─ .gitignore
├─ index.js
├─ LICENSE
├─ package.json
├─ preload.js
└─ src
    ├─ core
    │ ├─ global.js
    │ ├─ i18n.config.js
    │ └─ i18n.js (set restore user language)
    ├─ locales
    │ ├─ en.json
    │ └─ en-TW.json
    └─ resource
       ├─ css
       ├─ html
       ├─ img
       └─ plugin
````
i18n.config.js
````
const { I18n } = require('i18n');
const path = require('path');

const i18n = new I18n({
   locales: ['en', 'zh-TW'],
   defaultLocale: 'en',
   autoReload: true,
   extension: '.json',
   directory: path.join('./src', 'locales')
});

module.exports = i18n;
````

**Comment by Yomisana** [comment]
I just tried using the staticCatalog option as you said and it works!
Oh! Thanks for letting me know this is for server side node.js .Using it currently works I like the format too. :heart:

**Comment by mashpie** [comment]
glad to hear 👍
