### ISSUE TITLE
There are no 0.15.1 release and tag.

### ISSUE THREAD

**Issue by urapico** [mashpie/i18n-node#504]
Let me confirm that below.

There is 0.15.1 for npm package page. -> https://www.npmjs.com/package/i18n/v/0.15.1
But there are no release and tag for 0.15.1 at this GitHub repository.

I wonder that situation.
If you (@mashpie) have forgotten to push changes to GitHub, please push it. 🙇

**Comment by mashpie** [comment]
I mistaken a publish to mom without any code change. Will try to align releases and tags with next version.
