### ISSUE TITLE
feature request: support plurals with specific numbers

### ISSUE THREAD

**Issue by simplenotezy** [mashpie/i18n-node#514]
Awesome library. It lacks ability to specific specific amount in plurals, like so:

```json
"teammates_with": {
    "1": "friends with {friend}.",
    "2": "friends with {friend1} and {friend2}.",
    "3": "friends with {friend1}, {friend2} and 1 other.",
    "other": "friends with {friend1}, {friend2} and {value} others."
},
```

**Comment by simplenotezy** [comment]
For now I have achieved something similar like so:

```ts
export function tPlural(locale: string, path: string, count: number, replacements?: i18n.Replacements): string {
  const tryTranslationKey = `${path}.${count}`;

  const tryTranslation = t(locale, tryTranslationKey, replacements);

  if (tryTranslation === tryTranslationKey) {
    return t(locale, `${path}.other`, replacements);
  }

  return tryTranslation;
}

**Comment by mashpie** [comment]
there is messageformat support `i18n._mf()` (https://github.com/mashpie/i18n-node#i18n__mf) which looks to be helpful in your case: https://messageformat.github.io/messageformat/guide/#pluralformat and/or https://messageformat.github.io/messageformat/guide/#selectformat

**Comment by simplenotezy** [comment]
Interesting, thanks @mashpie for fast reply ⚡  - can you come with an example in terms of JSON?

The plural format described in https://messageformat.github.io/messageformat/guide/#pluralformat is unfamiliar to me - I'm not sure if our translation service (lokalise.com) event supports that format 🤔

**Comment by mashpie** [comment]
looking closer into your request I think you are looking for feature called __ranged interval support__ https://github.com/mashpie/i18n-node#ranged-interval-support] which allows you to define a range of numbers and a string to be used for each range. 

```json
{
  "teammates": "[1] friends with {friend}.|[2] friends with {friend1} and {friend2}.|[3] friends with {friend1}, {friend2} and 1 other.|friends with {friend1}, {friend2} and {value} others."
}
```
with ranges defined like this you can use the following code to get the correct string for each range, i.e.:

```js
__n('teammates', 6, { value: 4, friend1: 'Mattias', friend2: 'Marcus' }) // friends with Mattias, Marcus and 4 others.
__n('teammates', 2, { friend1: 'Mattias', friend2: 'Marcus' }) // friends with Mattias and Marcus.
```

**Comment by simplenotezy** [comment]
Aha, that's cool. Thanks!
