### ISSUE TITLE
how to generate json

### ISSUE THREAD

**Issue by guileen** [mashpie/i18n-node#8]
I read Readme.md, and it said "above code will automatically generate json", but how?

**Comment by willwong123** [comment]
Excuse me, If I have a lot of templates, so I need to request the template one by one? @mashpie

**Comment by mashpie** [comment]
right, a simple crawler could help.

**Comment by clintonb** [comment]
A crawler? That is quite inefficient. Coming from the Python+Django world,  Django's `makemessages` management command knows how to find all usages of the `gettext` method and extract strings. Has no one created something similar for NodeJS?

**Comment by mashpie** [comment]
you might find some scripts out in gist world. As extracting string depends much on how you were using i18n and it's api, it's quite an individual task to accomplish. Think of using `__()` inside a helper passing strings from a template for example. Impossible to grep those strings... For static strings you might consider this https://www.npmjs.com/package/i18n-extract - though I never played with that.

**Comment by clintonb** [comment]
Thanks. I ended up using i18n-abide. It used jsxgettext, which in turn uses a regex to find static strings. Since I am rendering a static site this is fine. Also, I can use format() for strings that need dynamic data. This is akin to what I am used to in Django.
