### ISSUE TITLE
Need to define locales

### ISSUE THREAD

**Issue by thenitai** [mashpie/i18n-node#81]
Hi there,

I was wondering if we *need* to list the available locales in the configuration of i18n? Can't the app simply see what is available in the /locales directory?

Thanks.

Kind Regards,
Nitai

**Comment by mashpie** [comment]
released, see https://github.com/mashpie/i18n-node#i18nconfigure and https://github.com/mashpie/i18n-node/blob/master/test/i18n.configureLocales.js
