### ISSUE TITLE
Integrate momentjs for automatically translating dates

### ISSUE THREAD

**Issue by manast** [mashpie/i18n-node#95]
What do you think about using momentjs language formatting support so that we could use the same global object __ when formatting dates?

It would be quite nice just to write: 

``` javascript
__(myDate, 'short')
// sv locale: 14/01/29

__(myDate, 'long')
// sv locale: 29:e January 2014
```

etc

**Comment by mashpie** [comment]
moment themselves tell to prefer `Intl` api. can be used side by side with `i18n` I tend not to implement any date, time or currency logik until we refactored to ES6 or even ESM.
